// Generated by npm run images:thumbnails after successful uploads.
// An empty manifest safely keeps originals until thumbnails are available.
export const cardImageThumbnails: Record<string, string> = {};
