export const funCharacterMap: Record<string, string[]> = {

//// FUN MOMENTS ONE ////

  "7-N-1": ["Princess Cadance, Twilight Sparkle, Discord"],
  "7-N-2": ["Breezies, Applejack, Fluttershy, Twilight Sparkle, Pinkie Pie, Rarity, Rainbow Dash"],
  "7-N-3": ["Rainbow Dash, Soarin"],
  "7-N-4": ["Applejack, Rainbow Dash, Twilight Sparkle, Rarity, Fluttershy, Pinkie Pie, Spike"],
  "7-N-5": ["Granny Smith, Big McIntosh, Apple Bloom, Applejack, Auntie Applesauce, Pinkie Pie"],
  "7-N-6": ["Rainbow Dash, Twilight Sparkle"],
  "7-N-7": ["Twilight Sparkle, Fluttershy, Rarity, Rainbow Dash, Applejack, Pinkie Pie"],
  "7-N-8": ["Pinkie Pie, Twilight Sparkle, Rarity"],
  "7-N-9": ["Sweetie Belle, Apple Bloom"],
  "7-N-10": ["Fluttershy"],
  "7-N-11": ["Twilight Sparkle"],
  "7-N-12": ["Twilight Sparkle"],
  "7-N-13": ["Flurry Heart"],
  "7-N-14": ["Rainbow Dash, Twilight Sparkle"],
  "7-N-15": ["Spike, Fluttershy, Pinkie Pie, Applejack, Rarity"],
  "7-N-16": ["Big McIntosh, Rarity, Fluttershy"],
  "7-N-17": ["Applejack, Apple Bloom"],
  "7-N-18": ["Twilight Sparkle"],
  "7-N-19": ["Twilight Sparkle, Rarity, Fluttershy, Pinkie Pie, Applejack, Rainbow Dash"],
  "7-N-20": ["Twilight Sparkle"],
  "7-SN-1": ["Princess Cadance, Twilight Sparkle, Discord"],
  "7-SN-2": ["Breezies, Applejack, Fluttershy, Twilight Sparkle, Pinkie Pie, Rarity, Rainbow Dash"],
  "7-SN-3": ["Rainbow Dash, Soarin"],
  "7-SN-4": ["Applejack, Rainbow Dash, Twilight Sparkle, Rarity, Fluttershy, Pinkie Pie, Spike"],
  "7-SN-5": ["Granny Smith, Big McIntosh, Apple Bloom, Applejack, Auntie Applesauce, Pinkie Pie"],
  "7-SN-6": ["Rainbow Dash, Twilight Sparkle"],
  "7-SN-7": ["Twilight Sparkle, Fluttershy, Rarity, Rainbow Dash, Applejack, Pinkie Pie"],
  "7-SN-8": ["Pinkie Pie, Twilight Sparkle, Rarity"],
  "7-SN-9": ["Sweetie Belle, Apple Bloom"],
  "7-SN-10": ["Fluttershy"],
  "7-SN-11": ["Twilight Sparkle"],
  "7-SN-12": ["Twilight Sparkle"],
  "7-SN-13": ["Flurry Heart"],
  "7-SN-14": ["Rainbow Dash, Twilight Sparkle"],
  "7-SN-15": ["Spike, Fluttershy, Pinkie Pie, Applejack, Rarity"],
  "7-SN-16": ["Big McIntosh, Rarity, Fluttershy"],
  "7-SN-17": ["Applejack, Apple Bloom"],
  "7-SN-18": ["Twilight Sparkle"],
  "7-SN-19": ["Twilight Sparkle, Rarity, Fluttershy, Pinkie Pie, Applejack, Rainbow Dash"],
  "7-SN-20": ["Twilight Sparkle"],
  "7-R-1": ["Twilight Sparkle"],
  "7-R-2": ["Pinkie Pie"],
  "7-R-3": ["Rainbow Dash"],
  "7-R-4": ["Rarity"],
  "7-R-5": ["Fluttershy, Angel"],
  "7-R-6": ["Applejack"],
  "7-R-7": ["Moon Dancer"],
  "7-R-8": ["Tree Hugger"],
  "7-R-9": ["Rose"],
  "7-R-10": ["Blossomforth"],
  "7-R-11": ["Golden Harvest"],
  "7-R-12": ["Angel Wings"],
  "7-R-13": ["Sheriff Silverstar"],
  "7-R-14": ["Quibble Pantss"],
  "7-R-15": ["DJ Pon-3"],
  "7-R-16": ["Princess Twilight Sparkle"],
  "7-R-17": ["Pinkie Pie"],
  "7-R-18": ["Rainbow Dash"],
  "7-R-19": ["Rarity"],
  "7-R-20": ["Fluttershy"],
  "7-R-21": ["Applejack"],
  "7-R-22": ["Spike"],
  "7-R-23": ["Cheese Sandwich"],
  "7-R-24": ["Cheerilee"],
  "7-R-25": ["Babs Seed"],
  "7-R-26": ["Diamond Tiara"],
  "7-R-27": ["Silver Spoon"],
  "7-R-28": ["Starlight Glimmer"],
  "7-R-29": ["Trixie"],
  "7-R-30": ["Lyra Heartstrings"],
  "7-R-31": ["Sweetie Drops"],
  "7-R-32": ["Muffins"],
  "7-R-33": ["Lily Valley"],
  "7-R-34": ["Daisy"],
  "7-R-35": ["Junebug"],
  "7-SR-1": ["Twilight Sparkle"],
  "7-SR-2": ["Pinkie Pie"],
  "7-SR-3": ["Rainbow Dash"],
  "7-SR-4": ["Rarity"],
  "7-SR-5": ["Fluttershy"],
  "7-SR-6": ["Applejack"],
  "7-SR-7": ["Princess Twilight Sparkle"],
  "7-SR-8": ["Sunburst"],
  "7-SR-9": ["Starlight Glimmer"],
  "7-SR-10": ["Big McIntosh"],
  "7-SR-11": ["Maud Pie"],
  "7-SR-12": ["Spitfire"],
  "7-SR-13": ["Flurry Heart"],
  "7-SR-14": ["Pizzelle"],
  "7-SR-15": ["Steven Magnet"],
  "7-SSR-1": ["Twilight Sparkle"],
  "7-SSR-2": ["Pinkie Pie"],
  "7-SSR-3": ["Rainbow Dash"],
  "7-SSR-4": ["Rarity"],
  "7-SSR-5": ["Fluttershy"],
  "7-SSR-6": ["Applejack"],
  "7-SSR-7": ["Snowfall Frost, Starlight Glimmer"],
  "7-SSR-8": ["Apple Bloom"],
  "7-SSR-9": ["Sweetie Belle"],
  "7-SSR-10": ["Scootaloo"],
  "7-SSR-11": ["Lyra Heartstrings"],
  "7-SSR-12": ["Spoiled Rich, Spoiled Milk"],
  "7-SSR-13": ["Diamond Tiara"],
  "7-SSR-14": ["DJ Pon-3"],
  "7-SSR-15": ["Golden Harvest"],
  "7-UR-1": ["Princess Twilight Sparkle"],
  "7-UR-2": ["Pinkie Pie"],
  "7-UR-3": ["Rainbow Dash"],
  "7-UR-4": ["Fluttershy"],
  "7-UR-5": ["Rarity"],
  "7-UR-6": ["Applejack"],
  "7-UR-7": ["Sweetie Belle"],
  "7-UR-8": ["Scootaloo"],
  "7-UR-9": ["Apple Bloom"],
  "7-UR-10": ["Cheese Sandwich"],
  "7-CR-1": ["Princess Twilight Sparkle"],
  "7-CR-2": ["Pinkie Pie"],
  "7-CR-3": ["Rainbow Dash"],
  "7-CR-4": ["Applejack"],
  "7-CR-5": ["Fluttershy"],
  "7-CR-6": ["Rarity"],
  "7-CR-7": ["Princess Celestia"],
  "7-CR-8": ["Princess Luna"],
  "7-CR-9": ["Princess Cadance"],
  "7-CR-10": ["Applejack, Rarity, Rarijack"],
  "7-CR-11": ["Starlight Glimmer, Twilight Sparkle, StarTwi, LightLight, Yuri"],
  "7-CR-12": ["Discord, Fluttershy, Fluttercord"],


  // FUN MOMENTS TWO //

  "8-N-1": ["Fluttershy, Rainbow Dash, Applejack, Rarity, Pinkie Pie"],
  "8-N-2": ["Pinkie Pie, Apple Bloom"],
  "8-N-3": ["Twilight Sparkle"],
  "8-N-4": ["Fluttershy"],
  "8-N-5": ["Starlight Glimmer, Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity"],
  "8-N-6": ["Granny Smith"],
  "8-N-7": ["Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity, Spike"],
  "8-N-8": ["Sandbar, Yona, Smolder, Ocellus, Silverstream, Gallus"],
  "8-N-9": ["Applejack, Big McIntosh, Apple Bloom, Granny Smith"],
  "8-N-10": ["Rainbow Dash, Applejack, Fluttershy, Twilight Sparkle, Rarity, Pinkie Pie, Spike"],
  "8-N-11": ["Spitfire, Rainbow Dash"],
  "8-N-12": ["Discord"],
  "8-N-13": ["Maud Pie"],
  "8-N-14": ["Spike, Rarity"],
  "8-N-15": ["Applejack, Pinkie Pie, Fluttershy, Rainbow Dash, Snails"],
  "8-N-16": ["Trixie, Starlight Glimmer"],
  "8-N-17": ["Flurry Heart, Twilighr Sparkle, Spike"],
  "8-N-18": ["Scootaloo, Bow Hothoof, Windy Whistles"],
  "8-N-19": ["Spike, Ember"],
  "8-N-20": ["Sandbar, Yona, Smolder, Ocellus, Silverstream, Gallus, Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity, Spike"],
  "8-SN-1": ["Fluttershy, Rainbow Dash, Applejack, Rarity, Pinkie Pie"],
  "8-SN-2": ["Pinkie Pie, Apple Bloom"],
  "8-SN-3": ["Twilight Sparkle"],
  "8-SN-4": ["Fluttershy"],
  "8-SN-5": ["Starlight Glimmer, Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity"],
  "8-SN-6": ["Granny Smith"],
  "8-SN-7": ["Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity, Spike"],
  "8-SN-8": ["Sandbar, Yona, Smolder, Ocellus, Silverstream, Gallus"],
  "8-SN-9": ["Applejack, Big McIntosh, Apple Bloom, Granny Smith"],
  "8-SN-10": ["Rainbow Dash, Applejack, Fluttershy, Twilight Sparkle, Rarity, Pinkie Pie, Spike"],
  "8-SN-11": ["Spitfire, Rainbow Dash"],
  "8-SN-12": ["Discord"],
  "8-SN-13": ["Maud Pie"],
  "8-SN-14": ["Spike, Rarity"],
  "8-SN-15": ["Applejack, Pinkie Pie, Fluttershy, Rainbow Dash, Snails"],
  "8-SN-16": ["Trixie, Starlight Glimmer"],
  "8-SN-17": ["Flurry Heart, Twilighr Sparkle, Spike"],
  "8-SN-18": ["Scootaloo, Bow Hothoof, Windy Whistles"],
  "8-SN-19": ["Spike, Ember"],
  "8-SN-20": ["Sandbar, Yona, Smolder, Ocellus, Silverstream, Gallus, Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity, Spike"],
  "8-R-1": ["Princess Twilight Sparkle"],
  "8-R-2": ["Pinkie Pie"],
  "8-R-3": ["Rainbow Dash"],
  "8-R-4": ["Rarity"],
  "8-R-5": ["Fluttershy"],
  "8-R-6": ["Applejack"],
  "8-R-7": ["Nurse Redheart"],
  "8-R-8": ["Cozy Glow"],
  "8-R-9": ["Toola Roola"],
  "8-R-10": ["Coconut Cream"],
  "8-R-11": ["Inky Rose"],
  "8-R-12": ["Prince Blueblood"],
  "8-R-13": ["Sunny Daze"],
  "8-R-14": ["Peachy Pie"],
  "8-R-15": ["Bulk Biceps"],
  "8-R-16": ["Randolph"],
  "8-R-17": ["Fleur De Lis"],
  "8-R-18": ["Trouble Shoes"],
  "8-R-19": ["Mr. Stripes"],
  "8-R-20": ["Plaid Stripes"],
  "8-R-21": ["Princess Twilight Sparkle"],
  "8-R-22": ["Pinkie Pie"],
  "8-R-23": ["Rainbow Dash"],
  "8-R-24": ["Rarity"],
  "8-R-25": ["Fluttershy"],
  "8-R-26": ["Applejack"],
  "8-R-27": ["Spike"],
  "8-R-28": ["Starlight Glimmer"],
  "8-R-29": ["Trixie"],
  "8-R-30": ["Lyra Heartstrings"],
  "8-R-31": ["Sweetie Drops"],
  "8-R-32": ["Muffins"],
  "8-R-33": ["Lily Valley"],
  "8-R-34": ["Daisy"],
  "8-R-35": ["Junebug"],
  "8-SR-1": ["Twilight Sparkle"],
  "8-SR-2": ["Pinkie Pie"],
  "8-SR-3": ["Rainbow Dash"],
  "8-SR-4": ["Fluttershy"],
  "8-SR-5": ["Rarity"],
  "8-SR-6": ["Applejack"],
  "8-SR-7": ["Princess Twilight Sparkle"],
  "8-SR-8": ["Apple Bloom"],
  "8-SR-9": ["Scootaloo"],
  "8-SR-10": ["Sweetie Belle"],
  "8-SR-11": ["Octavia"],
  "8-SR-12": ["Moon Dancer"],
  "8-SR-13": ["Twinkleshine"],
  "8-SR-14": ["Lemon Hearts"],
  "8-SR-15": ["Minuette"],
  "8-SSR-1": ["Princess Twilight Sparkle"],
  "8-SSR-2": ["Pinkie Pie"],
  "8-SSR-3": ["Rainbow Dash"],
  "8-SSR-4": ["Rarity"],
  "8-SSR-5": ["Fluttershy"],
  "8-SSR-6": ["Applejack"],
  "8-SSR-7": ["Princess Celestia"],
  "8-SSR-8": ["Princess Cadance"],
  "8-SSR-9": ["Spike"],
  "8-SSR-10": ["Diamond Tiara"],
  "8-SSR-11": ["Silver Spoon"],
  "8-SSR-12": ["Granny Smith"],
  "8-SSR-13": ["Big McIntosh"],
  "8-SSR-14": ["Cheerilee"],
  "8-SSR-15": ["Bulk Biceps"],
  "8-UR-1": ["Princess Twilight Sparkle"],
  "8-UR-2": ["Pinkie Pie"],
  "8-UR-3": ["Rainbow Dash"],
  "8-UR-4": ["Fluttershy"],
  "8-UR-5": ["Rarity"],
  "8-UR-6": ["Applejack"],
  "8-UR-7": ["Trixie"],
  "8-UR-8": ["Starlight Glimmer"],
  "8-UR-9": ["Princess Luna"],
  "8-UR-10": ["Princess Cadance"],
  "8-UGR-1": ["Princess Twilight Sparkle"],
  "8-UGR-2": ["Pinkie Pie"],
  "8-UGR-3": ["Rainbow Dash"],
  "8-UGR-4": ["Applejack"],
  "8-UGR-5": ["Fluttershy"],
  "8-UGR-6": ["Rarity"],
  "8-UGR-7": ["Apple Bloom"],
  "8-UGR-8": ["Scootaloo"],
  "8-UGR-9": ["Sweetie Belle"],
  "8-CR-1": ["Twilight Sparkle"],
  "8-CR-2": ["Pinkie Pie"],
  "8-CR-3": ["Rainbow Dash"],
  "8-CR-4": ["Applejack"],
  "8-CR-5": ["Fluttershy"],
  "8-CR-6": ["Rarity"],
  "8-CR-7": ["Starlight Glimmer"],
  "8-CR-8": ["Sunset Shimmer"],
  "8-CR-9": ["Spike"],
  "8-CR-10": ["Scootaloo, Sweetie Belle, Apple Bloom"],
  "8-CR-11": ["Pinkie Pie, Twilight Sparkle, TwiPie"],
  "8-CR-12": ["Applejack, Rainbow Dash, AppleDash"],

  /// FUN MOMENTS THREE ///

  "11-N-1": ["Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity, Princess Celestia, Princess Luna, Princess Cadance, Shining Armor, Flurry Heart"],
  "11-N-2": ["Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity, Spike"],
  "11-N-3": ["Twilight Sparkle"],
  "11-N-4": ["Starlight Glimmer, Princess Cadance, Spike, Flurry Heart"],
  "11-N-5": ["Pinkie Pie"],
  "11-N-6": ["Applejack, Apple Bloom"],
  "11-N-7": ["Rainbow Dash, Silverstream"],
  "11-N-8": [""],
  "11-N-9": ["Cozy Glow, Queen Chrysalis, Tirek"],
  "11-N-10": ["Fluttershy"],
  "11-N-11": ["Starlight Glimmer, Trixie"],
  "11-N-12": ["Princess Celestia, Princess Luna"],
  "11-N-13": ["Maud Pie"],
  "11-N-14": ["Sweetie Belle, Rarity"],
  "11-N-15": ["Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity"],
  "11-N-16": ["Applejack, Rainbow Dash, AppleDash"],
  "11-N-17": ["Apple Bloom, Scootaloo, Sweetie Belle"],
  "11-N-18": ["Cheese Sandwich, Pinkie Pie"],
  "11-N-19": ["Garble, Spike"],
  "11-N-20": ["Rarity, Big McIntosh, Toe Tapper, Torch Song"],
  "11-SN-1": ["Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity, Princess Celestia, Princess Luna, Princess Cadance, Shining Armor, Flurry Heart"],
  "11-SN-2": ["Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity, Spike"],
  "11-SN-3": ["Twilight Sparkle"],
  "11-SN-4": ["Starlight Glimmer, Princess Cadance, Spike, Flurry Heart"],
  "11-SN-5": ["Pinkie Pie"],
  "11-SN-6": ["Applejack, Apple Bloom"],
  "11-SN-7": ["Rainbow Dash, Silverstream"],
  "11-SN-8": [""],
  "11-SN-9": ["Cozy Glow, Queen Chrysalis, Tirek"],
  "11-SN-10": ["Fluttershy"],
  "11-SN-11": ["Starlight Glimmer, Trixie"],
  "11-SN-12": ["Princess Celestia, Princess Luna"],
  "11-SN-13": ["Maud Pie"],
  "11-SN-14": ["Sweetie Belle, Rarity"],
  "11-SN-15": ["Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity"],
  "11-SN-16": ["Applejack, Rainbow Dash, AppleDash"],
  "11-SN-17": ["Apple Bloom, Scootaloo, Sweetie Belle"],
  "11-SN-18": ["Cheese Sandwich, Pinkie Pie"],
  "11-SN-19": ["Garble, Spike"],
  "11-SN-20": ["Rarity, Big McIntosh, Toe Tapper, Torch Song"],
  "11-R-1": ["Princess Twilight Sparkle"],
  "11-R-2": ["Pinkie Pie"],
  "11-R-3": ["Rainbow Dash"],
  "11-R-4": ["Rarity"],
  "11-R-5": ["Fluttershy"],
  "11-R-6": ["Applejack"],
  "11-R-7": ["Nurse RedHeart"],
  "11-R-8": ["Cozy Glow"],
  "11-R-9": ["Toola Roola"],
  "11-R-10": ["Coconut Cream"],
  "11-R-11": ["Inky Rose"],
  "11-R-12": ["Prince Blueblood"],
  "11-R-13": ["Sunny Daze"],
  "11-R-14": ["Peachy Pie"],
  "11-R-15": ["Bulk Biceps"],
  "11-R-16": ["Princess Twilight Sparkle"],
  "11-R-17": ["Pinkie Pie"],
  "11-R-18": ["Rainbow Dash"],
  "11-R-19": ["Rarity"],
  "11-R-20": ["Fluttershy"],
  "11-R-21": ["Applejack"],
  "11-R-22": ["Spike"],
  "11-R-23": ["Prim Hemline"],
  "11-R-24": ["Hoity Toity"],
  "11-R-25": ["Photo Finish"],
  "11-R-26": ["Sapphire Shores"],
  "11-R-27": ["Fancy Pants"],
  "11-R-28": ["Svengallop"],
  "11-R-29": ["Tree Hugger"],
  "11-R-30": ["Sassy Saddles"],
  "11-R-31": ["Night Light"],
  "11-R-32": ["Twilight Velvet"],
  "11-R-33": ["Zephyr Breeze"],
  "11-R-34": ["Twist"],
  "11-R-35": ["Pipsqueak"],
  "11-SR-1": ["Princess Twilight Sparkle"],
  "11-SR-2": ["Princess Twilight Sparkle"],
  "11-SR-3": ["Pinkie Pie"],
  "11-SR-4": ["Pinkie Pie"],
  "11-SR-5": ["Rainbow Dash"],
  "11-SR-6": ["Rainbow Dash"],
  "11-SR-7": ["Fluttershy"],
  "11-SR-8": ["Fluttershy"],
  "11-SR-9": ["Rarity"],
  "11-SR-10": ["Rarity"],
  "11-SR-11": ["Applejack"],
  "11-SR-12": ["Applejack"],
  "11-SR-13": ["Spike"],
  "11-SR-14": ["Muffins"],
  "11-SR-15": ["Mayor Mare"],
  "11-SSR-1": ["Princess Twilight Sparkle"],
  "11-SSR-2": ["Pinkie Pie"],
  "11-SSR-3": ["Rainbow Dash"],
  "11-SSR-4": ["Rarity"],
  "11-SSR-5": ["Fluttershy"],
  "11-SSR-6": ["Applejack"],
  "11-SSR-7": ["Starlight Glimmer"],
  "11-SSR-8": ["Trixie"],
  "11-SSR-9": ["Princess Luna"],
  "11-SSR-10": ["Countess Coloratura"],
  "11-SSR-11": ["Vapor Trail"],
  "11-SSR-12": ["Muffins"],
  "11-SSR-13": ["Sugar Belle"],
  "11-SSR-14": ["Lightning Dust"],
  "11-SSR-15": ["Spitfire"],
  "11-UR-1": ["Princess Twilight Sparkle"],
  "11-UR-2": ["Pinkie Pie"],
  "11-UR-3": ["Rainbow Dash"],
  "11-UR-4": ["Rarity"],
  "11-UR-5": ["Fluttershy"],
  "11-UR-6": ["Applejack"],
  "11-UR-7": ["Apple Bloom, Applejack"],
  "11-UR-8": ["Scootaloo, Rainbow Dash"],
  "11-UR-9": ["Sweetie Belle, Rarity"],
  "11-UR-10": ["DJ Pon-3"],
  "11-UGR-1": ["Princess Twilight Sparkle"],
  "11-UGR-2": ["Pinkie Pie"],
  "11-UGR-3": ["Rainbow Dash"],
  "11-UGR-4": ["Rarity"],
  "11-UGR-5": ["Fluttershy"],
  "11-UGR-6": ["Applejack"],
  "11-UGR-7": ["Spike"],
  "11-UGR-8": ["Starlight Glimmer"],
  "11-UGR-9": ["Trixie"],
  "11-CR-1": ["Twilight Sparkle"],
  "11-CR-2": ["Pinkie Pie"],
  "11-CR-3": ["Rainbow Dash"],
  "11-CR-4": ["Rarity"],
  "11-CR-5": ["Fluttershy"],
  "11-CR-6": ["Applejack"],
  "11-CR-7": ["Princess Celestia"],
  "11-CR-8": ["Princess Luna"],
  "11-CR-9": ["Princess Cadance"],
  "11-CR-10": ["Twilight Sparkle, Rainbow Dash, TwiDash"],
  "11-CR-11": ["Applejack, Rarity, RariJack"],
  "11-CR-12": ["Rainbow Dash, Pinkie Pie, Applejack, Twilight Sparkle, Fluttershy, Rarity"],
  "11-SCR-1": ["Twilight Sparkle"],
  "11-SCR-2": ["Pinkie Pie"],
  "11-SCR-3": ["Rainbow Dash"],
  "11-SCR-4": ["Rarity"],
  "11-SCR-5": ["Fluttershy"],
  "11-SCR-6": ["Applejack"],
  "11-SCR-7": ["Starswirl the Bearded"],
  "11-SCR-8": ["Somnambula"],
  "11-SCR-9": ["Flash Magnus"],
  "11-SCR-10": ["Mistmane"],
  "11-SCR-11": ["Mage Meadowbrook"],
  "11-SCR-12": ["Rockhoof"],
};