export const rainbowCharacterMap: Record<string, string[]> = {


    /// RAINBOW ONE ///


    "5-R-1": ["Princess Twilight Sparkle"],
  "5-R-2": ["Pinkie Pie"],
  "5-R-3": ["Rainbow Dash"],
  "5-R-4": ["Rarity"],
  "5-R-5": ["Fluttershy"],
  "5-R-6": ["Applejack"],
  "5-R-7": ["Spike"],
  "5-R-8": ["Bow Hothoof"],
  "5-R-9": ["Windy Whistles"],
  "5-R-10": ["Fancy Pants"],
  "5-R-11": ["Sassy Saddles"],
  "5-R-12": ["Moon Dancer"],
  "5-R-13": ["Tree Hugger"],
  "5-R-14": ["Rose"],
  "5-R-15": ["Blossomforth"],
  "5-R-16": ["Golden Harvest"],
  "5-R-17": ["Angel Wings"],
  "5-R-18": ["Sheriff Silverstar"],
  "5-R-19": ["Quibble Pants"],
  "5-R-20": ["DJ Pon-3"],
  "5-R-21": ["Princess Twilight Sparkle"],
  "5-R-22": ["Pinkie Pie"],
  "5-R-23": ["Rainbow Dash"],
  "5-R-24": ["Rarity"],
  "5-R-25": ["Fluttershy"],
  "5-R-26": ["Applejack"],
  "5-R-27": ["Hayseed Turnip Truck"],
  "5-R-28": ["Auntie Applesauce, Applesauce"],
  "5-R-29": ["Apple Strudel"],
  "5-R-30": ["Igneous Rock Pie"], 
    "5-SR-1": ["Princess Twilight Sparkle"],
  "5-SR-2": ["Pinkie Pie"],
  "5-SR-3": ["Rainbow Dash"],
  "5-SR-4": ["Rarity"],
  "5-SR-5": ["Fluttershy"],
  "5-SR-6": ["Applejack"],
  "5-SR-7": ["Princess Twilight Sparkle"],
  "5-SR-8": ["Auntie Applesauce, Applesauce"],
  "5-SR-9": ["Pear Butter"],
  "5-SR-10": ["Bright Mac"],
  "5-SR-11": ["Muffins"],
  "5-SR-12": ["Countess Coloratura"],
  "5-SR-13": ["Spike"],
  "5-SR-14": ["Autumn Blaze"],
  "5-SR-15": ["Orthros"],
    "5-FR-1": ["Princess Twilight Sparkle"],
  "5-FR-2": ["Pinkie Pie"],
  "5-FR-3": ["Rarity"],
  "5-FR-4": ["Fluttershy"],
  "5-FR-5": ["Applejack"],
  "5-FR-6": ["Rainbow Dash"],
  "5-FR-7": ["Spike"],
  "5-FR-8": ["Starlight Glimmer"],
  "5-FR-9": ["Sunburst"],
  "5-FR-10": ["Trixie"],
  "5-FR-11": ["Vapor Trail"],
  "5-FR-12": ["Maud Pie"],
  "5-FR-13": ["Strawberry Sunrise"],
  "5-FR-14": ["Inky Rose"],
  "5-FR-15": ["Photo Finish"],
  "5-FR-16": ["Pipsqueak"],
  "5-FR-17": ["Autumn Blaze"],
  "5-FR-18": ["Cheese Sandwich"],
    "5-TR-1": ["Princess Twilight Sparkle"],
  "5-TR-2": ["Pinkie Pie"],
  "5-TR-3": ["Rarity"],
  "5-TR-4": ["Fluttershy"],
  "5-TR-5": ["Applejack"],
  "5-TR-6": ["Rainbow Dash"],
  "5-TR-7": ["Princess Celestia"],
  "5-TR-8": ["Princess Luna"],
  "5-TR-9": ["Princess Cadance"],
  "5-TR-10": ["Cheese Sandwich"],
  "5-TR-11": ["Sweetie Drops"],
  "5-TR-12": ["Lyra Heartstrings"],
    "5-TGR-1": ["Princess Twilight Sparkle"],
  "5-TGR-2": ["Pinkie Pie"],
  "5-TGR-3": ["Rarity"],
  "5-TGR-4": ["Fluttershy"],
  "5-TGR-5": ["Applejack"],
  "5-TGR-6": ["Rainbow Dash"],
  "5-TGR-7": ["Starlight Glimmer"],
  "5-TGR-8": ["Trixie"],
    "5-MTR-1": ["Princess Twilight Sparkle"],
  "5-MTR-2": ["Princess Twilight Sparkle"],
  "5-MTR-3": ["Pinkie Pie"],
  "5-MTR-4": ["Pinkie Pie"],
  "5-MTR-5": ["Rarity"],
  "5-MTR-6": ["Rarity"],
  "5-MTR-7": ["Fluttershy"],
  "5-MTR-8": ["Fluttershy"],
  "5-MTR-9": ["Applejack"],
  "5-MTR-10": ["Applejack"],
  "5-MTR-11": ["Rainbow Dash"],
  "5-MTR-12": ["Rainbow Dash"],
  "5-MTR-13": ["Princess Celestia"],
  "5-MTR-14": ["Princess Celestia"],
  "5-MTR-15": ["Princess Luna"],
  "5-MTR-16": ["Princess Luna"],
  "5-MTR-17": ["Princess Cadance"],
  "5-MTR-18": ["Princess Cadance"],
    "5-SSR-1": ["Princess Twilight Sparkle"],
  "5-SSR-2": ["Pinkie Pie"],
  "5-SSR-3": ["Rainbow Dash"],
  "5-SSR-4": ["Rarity"],
  "5-SSR-5": ["Fluttershy"],
  "5-SSR-6": ["Applejack"],
  "5-SSR-7": ["Starlight Glimmer"],
  "5-SSR-8": ["Trixie"],
  "5-SSR-9": ["Discord"],
  "5-SSR-10": ["Spike"],
  "5-SSR-11": ["Princess Cadance"],
  "5-SSR-12": ["Shining Armor"],
  "5-SSR-13": ["Princess Flurry Heart"],
  "5-SSR-14": ["Pipsqueak"],
  "5-SSR-15": ["Mayor Mare"],
    "5-UR-1": ["Princess Twilight Sparkle"],
  "5-UR-2": ["Pinkie Pie"],
  "5-UR-3": ["Rainbow Dash"],
  "5-UR-4": ["Fluttershy"],
  "5-UR-5": ["Rarity"],
  "5-UR-6": ["Applejack"],
  "5-UR-7": ["Spike"],
  "5-UR-8": ["Princess Celestia"],
  "5-UR-9": ["Princess Luna"],
  "5-UR-10": ["Princess Cadance"],
  "5-UR-11": ["Shining Armor"],
  "5-UR-12": ["Princess Flurry Heart"],
  "5-UR-13": ["Sunset Shimmer"],
  "5-UR-14": ["Starlight Glimmer"],
  "5-UR-15": ["Trixie"],
    "5-USR-1": ["Princess Twilight Sparkle"],
  "5-USR-2": ["Pinkie Pie"],
  "5-USR-3": ["Rarity"],
  "5-USR-4": ["Fluttershy"],
  "5-USR-5": ["Applejack"],
  "5-USR-6": ["Rainbow Dash"],
  "5-USR-7": ["Princess Cadance"],
  "5-USR-8": ["Princess Flurry Heart"],
    "5-XR-1": ["Princess Twilight Sparkle"],
  "5-XR-2": ["Pinkie Pie"],
  "5-XR-3": ["Rarity"],
  "5-XR-4": ["Fluttershy"],
  "5-XR-5": ["Applejack"],
  "5-XR-6": ["Rainbow Dash"],
  "5-XR-7": ["Sunset Shimmer"],

 /// RAINBOW TWO ///

  "6-BASE-1": [""],
  "6-BASE-2": [""],
  "6-BASE-3": [""],
  "6-BASE-4": [""],
  "6-BASE-5": [""],
  "6-BASE-6": [""],
  "6-BASE-7": [""],
  "6-BASE-8": [""],
  "6-BASE-9": [""],
  "6-BASE-10": [""],
  "6-BASE-11": [""],
  "6-BASE-12": [""],
  "6-BASE-13": [""],
  "6-BASE-14": [""],
  "6-BASE-15": [""],
  "6-BASE-16": [""],
  "6-BASE-17": [""],
  "6-BASE-18": [""],
  "6-R-1": ["Princess Twilight Sparkle"],
  "6-R-2": ["Pinkie Pie"],
  "6-R-3": ["Rainbow Dash"],
  "6-R-4": ["Rarity"],
  "6-R-5": ["Fluttershy"],
  "6-R-6": ["Applejack"],
  "6-R-7": ["Nurse Redheart"],
  "6-R-8": ["Cozy Glow"],
  "6-R-9": ["Toola Roola"],
  "6-R-10": ["Coconut Cream"],
  "6-R-11": ["Inky Rose"],
  "6-R-12": ["Prince Blueblood"],
  "6-R-13": ["Sunny Daze"],
  "6-R-14": ["Peachy Pie"],
  "6-R-15": ["Bulk Biceps"],
  "6-R-16": ["Princess Twilight Sparkle"],
  "6-R-17": ["Pinkie Pie"],
  "6-R-18": ["Rainbow Dash"],
  "6-R-19": ["Rarity"],
  "6-R-20": ["Fluttershy"],
  "6-R-21": ["Applejack"],
  "6-R-22": ["Spike"],
  "6-R-23": ["Prim Hemline"],
  "6-R-24": ["Hoity Toity"],
  "6-R-25": ["Photo Finish"],
  "6-R-26": ["Sapphire Shores"],
  "6-R-27": ["Fancy Pants"],
  "6-R-28": ["Svengallop"],
  "6-R-29": ["Tree Hugger"],
  "6-R-30": ["Sassy Saddles"],
  "6-SR-1": ["Princess Twilight Sparkle"],
  "6-SR-2": ["Pinkie Pie"],
  "6-SR-3": ["Rainbow Dash"],
  "6-SR-4": ["Fluttershy"],
  "6-SR-5": ["Rarity"],
  "6-SR-6": ["Applejack"],
  "6-SR-7": ["Spike"],
  "6-SR-8": ["Muffins"],
  "6-SR-9": ["Mayor Mare"],
  "6-SR-10": ["Sweetie Belle"],
  "6-SR-11": ["Princess Luna"],
  "6-SR-12": ["Fluttershy, Discord, Fluttercord"],
  "6-SR-13": ["Spitfire"],
  "6-SR-14": ["Babs Seed"],
  "6-ST-1": ["Princess Twilight Sparkle"],
  "6-ST-2": ["Pinkie Pie"],
  "6-ST-3": ["Rainbow Dash"],
  "6-ST-4": ["Rarity"],
  "6-ST-5": ["Fluttershy"],
  "6-ST-6": ["Applejack"],
  "6-ST-7": ["Apple Bloom"],
  "6-ST-8": ["Scootaloo"],
  "6-ST-9": ["Sweetie Belle"],
  "6-ST-10": ["Sugar Belle"],
  "6-ST-11": ["Princess Cadance"],
  "6-ST-12": ["Starlight Glimmer"],
  "6-ST-13": ["Princess Twilight Sparkle"],
  "6-ST-14": ["Pinkie Pie"],
  "6-ST-15": ["Rainbow Dash"],
  "6-ST-16": ["Rarity"],
  "6-ST-17": ["Fluttershy"],
  "6-ST-18": ["Applejack"],
  "6-ST-19": ["Queen Chrysalis"],
  "6-ST-20": ["Mistmane"],
  "6-SSR-1": ["Princess Twilight Sparkle"],
  "6-SSR-2": ["Pinkie Pie"],
  "6-SSR-3": ["Rainbow Dash"],
  "6-SSR-4": ["Rarity"],
  "6-SSR-5": ["Fluttershy"],
  "6-SSR-6": ["Applejack"],
  "6-SSR-7": ["Spike"],
  "6-SSR-8": ["Starlight Glimmer"],
  "6-SSR-9": ["Maud Pie"],
  "6-SSR-10": ["Apple Bloom"],
  "6-SSR-11": ["Granny Smith"],
  "6-SSR-12": ["Zecora"],
  "6-SSR-13": ["Mrs. Cup Cake"],
  "6-SSR-14": ["Mr. Carrot Cake"],
  "6-SSR-15": ["Daring Do"],
  "6-FR-1": ["Princess Twilight Sparkle"],
  "6-FR-2": ["Pinkie Pie"],
  "6-FR-3": ["Rainbow Dash"],
  "6-FR-4": ["Rarity"],
  "6-FR-5": ["Fluttershy"],
  "6-FR-6": ["Applejack"],
  "6-FR-7": ["Spike"],
  "6-FR-8": ["Cherry Jubilee"],
  "6-FR-9": ["Prince Blueblood"],
  "6-FR-10": ["Matilda"],
  "6-FR-11": ["Suri Polomare"],
  "6-FR-12": ["Countess Coloratura"],
  "6-FR-13": ["Bulk Biceps"],
  "6-FR-14": ["Fancy Pants"],
  "6-FR-15": ["Lightning Dust"],
  "6-FR-16": ["Twist"],
  "6-FR-17": ["Blossomforth"],
  "6-FR-18": ["Thunderlane"],
  "6-TR-1": ["Princess Twilight Sparkle"],
  "6-TR-2": ["Pinkie Pie"],
  "6-TR-3": ["Rainbow Dash"],
  "6-TR-4": ["Rarity"],
  "6-TR-5": ["Fluttershy"],
  "6-TR-6": ["Applejack"],
  "6-TR-7": ["Apple Bloom"],
  "6-TR-8": ["Scootaloo"],
  "6-TR-9": ["Sweetie Belle"],
  "6-TR-10": ["Sugar Belle"],
  "6-TR-11": ["Princess Cadance"],
  "6-TR-12": ["Starlight Glimmer"],
  "6-TGR-1": ["Princess Twilight Sparkle"],
  "6-TGR-2": ["Pinkie Pie"],
  "6-TGR-3": ["Rainbow Dash"],
  "6-TGR-4": ["Rarity"],
  "6-TGR-5": ["Fluttershy"],
  "6-TGR-6": ["Applejack"],
  "6-TGR-7": ["Queen Chrysalis"],
  "6-TGR-8": ["Mistmane"],
  "6-UR-1": ["Princess Twilight Sparkle"],
  "6-UR-2": ["Pinkie Pie"],
  "6-UR-3": ["Rainbow Dash"],
  "6-UR-4": ["Rarity"],
  "6-UR-5": ["Fluttershy"],
  "6-UR-6": ["Applejack"],
  "6-UR-7": ["Apple Bloom, Applejack"],
  "6-UR-8": ["Scootaloo, Rainbow Dash"],
  "6-UR-9": ["Sweetie Belle, Rarity"],
  "6-UR-10": ["DJ Pon-3"],
  "6-UR-11": ["Photo Finish"],
  "6-UR-12": ["Cozy Glow"],
  "6-UR-13": ["Diamond Tiara"],
  "6-UR-14": ["Princess Twilight Sparkle"],
  "6-UR-15": ["Pinkie Pie"],
  "6-UR-16": ["Rainbow Dash"],
  "6-UR-17": ["Rarity"],
  "6-UR-18": ["Fluttershy"],
  "6-UR-19": ["Applejack"],
  "6-USR-1": ["Princess Twilight Sparkle"],
  "6-USR-2": ["Pinkie Pie"],
  "6-USR-3": ["Rainbow Dash"],
  "6-USR-4": ["Rarity"],
  "6-USR-5": ["Fluttershy"],
  "6-USR-6": ["Applejack"],
  "6-USR-7": ["Starlight Glimmer"],
  "6-USR-8": ["Trixie"],
  "6-XR-1": ["Princess Twilight Sparkle"],
  "6-XR-2": ["Pinkie Pie"],
  "6-XR-3": ["Rainbow Dash"],
  "6-XR-4": ["Rarity"],
  "6-XR-5": ["Fluttershy"],
  "6-XR-6": ["Applejack"],
  "6-XR-7": ["Spike"],
  "6-XR-8": ["Discord, Twilight Sparkle, Pinkie Pie, Rarity, Fluttershy, Rainbow Dash, Applejack"],

};