export const TCGCharacterMap: Record<string, string[]> = {


    // FRIENDSHIPS BEGIN //


  "SD-C-1": ["Twilight Sparkle"],
  "SD-C-2": ["Fluttershy"],
  "SD-C-3": ["Pinkie Pie"],
  "SD-C-4": ["Applejack"],
  "SD-C-5": ["Rainbow Dash"],
  "SD-C-6": ["Rarity"],
  "SD-C-7": ["Apple Bloom"],
  "SD-C-8": ["Sweetie Belle"],
  "SD-C-9": ["Scootaloo"],
  "SD-U-1": ["Twilight Sparkle"],
  "SD-U-2": ["Fluttershy"],
  "SD-U-3": ["Pinkie Pie"],
  "SD-U-4": ["Applejack"],
  "SD-U-5": ["Rainbow Dash"],
  "SD-U-6": ["Rarity"],
  "SD-U-7": ["Zecora"],
  "SD-SR-1": ["Twilight Sparkle"],
  "SD-SR-2": ["Fluttershy"],
  "SD-SR-3": ["Pinkie Pie"],
  "SD-SR-4": ["Applejack"],
  "SD-SR-5": ["Rainbow Dash"],
  "SD-SR-6": ["Rarity"],
  "SD-SPR-1": ["Fluttershy"],
  "SD-SPR-2": ["Scootaloo"],
  "SD-SPR-3": ["Twilight Sparkle, Spike, Owlowiscious"],
  "SD-SPR-4": ["Twilight Sparkle, Rarity, Applejack, Pinkie Pie, Rainbow Dash, Fluttershy"],
  "SD-SPR-5": ["Cheerilee, Apple Bloom, Twist, Silver Spoon, Diamond Tiara, Sweetie Belle"],
  "SD-SPR-6": ["Twilight Sparkle, Rarity, Applejack, Pinkie Pie, Rainbow Dash, Fluttershy, Apple Bloom, Sweetie Belle, Spike, Scootaloo"],
  "SD-SPR-7": ["Pinkie Pie"],
  "SD-SPR-8": [""],
  "SD-SPR-9": [""],
  "SD-SPR-10": ["Zecora"],
  "SD-GR-1": ["Twilight Sparkle"],
  "SD-GR-2": ["Fluttershy, Angel"],
  "SD-GR-3": ["Pinkie Pie"],
  "SD-GR-4": ["Applejack"],
  "SD-GR-5": ["Rainbow Dash"],
  "SD-GR-6": ["Rarity"],
  "SD-CR-1": ["Twilight Sparkle, Spike"],
  "SD-CR-2": ["Fluttershy, Angel"],
  "SD-CR-3": ["Pinkie Pie, Gummy"],
  "SD-CR-4": ["Applejack, Scootaloo, Sweetie Belle, Apple Bloom"],
  "SD-CR-5": ["Rainbow Dash, Spitfire, Fleet Foot"],
  "SD-CR-6": ["Rarity, Opalescence"],
  "SD-ER-1": [""],
  "SD-ER-2": [""],
  "SD-ER-3": [""],
  "SD-ER-4": [""],
  "SD-ER-5": [""],
  "SD-ER-6": [""],
  "SD-PER-7": [""],
  "SD-PER-8": [""],
  "SD-PER-9": [""],
  "SD-PER-10": [""],
  "SD-PER-11": [""],
  "SD-PER-12": [""],
  "SD-PER-13": [""],
  "SD-PER-14": [""],
  "SD-PER-15": [""],
  "SD-PER-16": [""],
  "SD-PER-17": [""],
  "SD-PER-18": [""],
  "SD-PRR-1": ["Twilight Sparkle"],
  "SD-PRR-2": ["Fluttershy"],
  "SD-PRR-3": ["Pinkie Pie"],
  "SD-PRR-4": ["Applejack"],
  "SD-PRR-5": ["Rainbow Dash"],
  "SD-PRR-6": ["Rarity"],

  //// FANTASY WONDERLAND ////


"FW-C-1": ["Twilight Sparkle"],
"FW-C-2": ["Twilight Sparkle"],
"FW-C-3": ["Twilight Sparkle"],
"FW-C-4": ["Fluttershy"],
"FW-C-5": ["Fluttershy"],
"FW-C-6": ["Pinkie Pie"],
"FW-C-7": ["Pinkie Pie"],
"FW-C-8": ["Applejack"],
"FW-C-9": ["Applejack"],
"FW-C-10": ["Rainbow Dash"],
"FW-C-11": ["Rainbow Dash"],
"FW-C-12": ["Rarity"],
"FW-C-13": ["Rarity"],
"FW-C-14": ["Spike"],
"FW-C-15": ["Apple Bloom"],
"FW-C-16": ["Sweetie Belle"],
"FW-C-17": ["Scootaloo"],
"FW-C-18": ["Big McIntosh"],
"FW-C-19": ["Granny Smith"],
"FW-C-20": ["Trixie"],
"FW-C-21": ["Gilda"],
"FW-C-22": ["Diamond Tiara"],
"FW-C-23": ["Silver Spoon"],
"FW-C-24": ["Mayor Mare"],
"FW-C-25": ["Twilight Sparkle, Spike"],
"FW-C-26": ["Twilight Sparkle, Rarity, Applejack, Pinkie Pie, Rainbow Dash, Fluttershy"],
"FW-C-27": ["Twilight Sparkle, Rarity, Applejack, Pinkie Pie, Rainbow Dash, Fluttershy, Spike"],
"FW-C-28": ["Twilight Sparkle, Rarity, Applejack, Pinkie Pie, Rainbow Dash, Fluttershy"],
"FW-C-29": ["Fluttershy, Philomena"],
"FW-C-30": ["Fluttershy, Philomena"],
"FW-C-31": ["Fluttershy, Philomena"],
"FW-C-32": ["Fluttershy, Philomena"],
"FW-C-33": ["Pinkie Pie, Fluttershy, Rainbow Dash"],
"FW-C-34": ["Pinkie Pie, Twilight Sparkle"],
"FW-C-35": ["Pinkie Pie, Gummy"],
"FW-C-36": ["Twilight Sparkle, Rarity, Applejack, Pinkie Pie, Rainbow Dash, Fluttershy"],
"FW-C-37": ["Applejack, Bloomberg"],
"FW-C-38": ["Little StrongHeart, Chief Thunderhooves"],
"FW-C-39": ["Chief Thunderhooves, Sheriff Silverstar, Applejack"],
"FW-C-40": ["Applejack, Bloomberg"],
"FW-C-41": ["Pinkie Pie, Rainbow Dash, Gilda"],
"FW-C-42": ["Pinkie Pie, Rainbow Dash, Gilda"],
"FW-C-43": ["Pinkie Pie, Rainbow Dash, Gilda, Spike, Twilight Sparkle"],
"FW-C-44": ["Twilight Sparkle, Rarity, Applejack, Pinkie Pie, Rainbow Dash, Fluttershy, Sweetie Drops, Spike, White Lightning"],
"FW-C-45": ["Twilight Sparkle, Rarity, Applejack, Pinkie Pie, Rainbow Dash, Fluttershy"],
"FW-C-46": ["Rarity"],
"FW-C-47": ["Twilight Sparkle, Rarity, Applejack, Pinkie Pie, Fluttershy"],
"FW-C-48": ["Twilight Sparkle, Rarity, Applejack, Pinkie Pie, Rainbow Dash, Fluttershy"],
"FW-U-1": ["Twilight Sparkle"],
"FW-U-2": ["Twilight Sparkle"],
"FW-U-3": ["Fluttershy"],
"FW-U-4": ["Fluttershy"],
"FW-U-5": ["Pinkie Pie"],
"FW-U-6": ["Pinkie Pie"],
"FW-U-7": ["Applejack"],
"FW-U-8": ["Applejack"],
"FW-U-9": ["Rainbow Dash"],
"FW-U-10": ["Rainbow Dash"],
"FW-U-11": ["Rarity"],
"FW-U-12": ["Rarity"],
"FW-U-13": ["Spike"],
"FW-U-14": ["Spike"],
"FW-U-15": ["Apple Bloom"],
"FW-U-16": ["Sweetie Belle"],
"FW-U-17": ["Scootaloo"],
"FW-U-18": ["Trixie"],
"FW-ER-7": [""],
"FW-ER-8": [""],
"FW-ER-9": [""],
"FW-ER-10": [""],
"FW-ER-11": [""],
"FW-ER-12": [""],
"FW-SR-1": ["Twilight Sparkle, Owlowiscious"],
"FW-SR-2": ["Fluttershy, Angel"],
"FW-SR-3": ["Pinkie Pie, Gummy"],
"FW-SR-4": ["Applejack, Winona"],
"FW-SR-5": ["Rainbow Dash, Tank"],
"FW-SR-6": ["Rarity, Opalescence"],
"FW-SR-7": ["Owlowiscious, Twilight Sparkle"],
"FW-SR-8": ["Angel, Fluttershy"],
"FW-SR-9": ["Gummy, Pinkie Pie"],
"FW-SR-10": ["Winona, Applejack"],
"FW-SR-11": ["Tank, Rainbow Dash"],
"FW-SR-12": ["Opalescence, Rarity"],
"FW-SR-13": ["Zecora"],
"FW-SR-14": ["Trixie"],
"FW-SPR-1": ["Rainbow Dash"],
"FW-SPR-2": ["Fluttershy"],
"FW-SPR-3": ["Spike"],
"FW-SPR-4": ["Twilight Sparkle"],
"FW-SPR-5": ["Pinkie Pie"],
"FW-SPR-6": ["Granny Smith"],
"FW-SPR-7": ["Applejack, Rarity, Raridash"],
"FW-SPR-8": ["Twilight Sparkle"],
"FW-SPR-9": ["Rarity"],
"FW-SPR-10": ["Scootaloo, Sweetie Belle, Apple Bloom"],
"FW-SPR-11": ["Pinkie Pie"],
"FW-SPR-12": ["Applejack"],
"FW-SPR-13": ["Fluttershy"],
"FW-SPR-14": ["Fluttershy"],
"FW-SPR-15": ["Apple Bloom"],
"FW-SPR-16": ["Spike"],
"FW-SPR-17": ["Fluttershy, Philomena"],
"FW-SPR-18": ["Spike"],
"FW-SPR-19": ["Scootaloo, Sweetie Belle, Apple Bloom"],
"FW-SPR-20": ["Twilight Sparkle"],
"FW-SPR-21": ["Owlowiscious"],
"FW-SPR-22": ["Spike"],
"FW-SPR-23": [""],
"FW-SPR-24": [""],
"FW-SPR-25": ["Pinkie Pie"],
"FW-SPR-26": ["Opalescence"],
"FW-SPR-27": ["Fluttershy"],
"FW-SPR-28": [""],
"FW-GR-1": ["Twilight Sparkle"],
"FW-GR-2": ["Fluttershy"],
"FW-GR-3": ["Pinkie Pie"],
"FW-GR-4": ["Applejack"],
"FW-GR-5": ["Rainbow Dash"],
"FW-GR-6": ["Rarity"],
"FW-GR-7": ["Twilight Sparkle"],
"FW-GR-8": ["Fluttershy"],
"FW-GR-9": ["Pinkie Pie"],
"FW-GR-10": ["Applejack"],
"FW-GR-11": ["Rainbow Dash"],
"FW-GR-12": ["Rarity"],
"FW-CR-1": ["Twilight Sparkle, Pinkie Pie, Spike"],
"FW-CR-2": ["Fluttershy, Rainbow Dash"],
"FW-CR-3": ["Pinkie Pie, Twilight Sparkle"],
"FW-CR-4": ["Applejack, Rarity"],
"FW-CR-5": ["Rainbow Dash, Fluttershy"],
"FW-CR-6": ["Rarity, Applejack"],
"FW-CR-7": ["Twilight Sparkle, Spike"],
"FW-CR-8": ["Fluttershy, Angel"],
"FW-CR-9": ["Pinkie Pie, Gummy, Fluttershy"],
"FW-CR-10": ["Applejack, Sweetie Belle, Scootaloo, Apple Bloom"],
"FW-CR-11": ["Rainbow Dash, Soarin, Spitfire"],
"FW-CR-12": ["Rarity, Opalescence"],
"FW-RR-1": ["Twilight Sparkle"],
"FW-RR-2": ["Fluttershy"],
"FW-RR-3": ["Pinkie Pie"],
"FW-RR-4": ["Applejack"],
"FW-RR-5": ["Rainbow Dash"],
"FW-RR-6": ["Rarity"],
"FW-PER-1": [""],
"FW-PER-2": [""],
"FW-PER-3": [""],
"FW-PER-4": [""],
"FW-PER-5": [""],
"FW-PER-6": [""],
"FW-PER-7": [""],
"FW-PER-8": [""],
"FW-PER-9": [""],
"FW-PER-10": [""],
"FW-PER-11": [""],
"FW-PER-12": [""],
"FW-PSPR-1": ["Rainbow Dash"],
"FW-PSPR-2": ["Fluttershy"],
"FW-PSPR-3": ["Spike"],
"FW-PSPR-4": ["Pinkie Pie"],
"FW-PSPR-5": ["Rarity, Applejack, RariJack"],
"FW-PSPR-6": ["Twilight Sparkle"],
"FW-PSPR-7": ["Rarity"],
"FW-PSPR-8": ["Applejack"],
"FW-PSPR-9": ["Fluttershy, Spike"],
"FW-PSPR-10": ["Spike"],
"FW-PSPR-11": ["Owlowiscious"],
"FW-PGR-1": ["Twilight Sparkle, Spike, Princess Celestia"],
"FW-PGR-2": ["Fluttershy, Angel"],
"FW-PGR-3": ["Pinkie Pie"],
"FW-PGR-4": ["Applejack"],
"FW-PGR-5": ["Rainbow Dash"],
"FW-PGR-6": ["Rarity"],
"FW-PCR-1": ["Twilight Sparkle, Spike"],
"FW-PCR-2": ["Fluttershy"],
"FW-PCR-3": ["Pinkie Pie"],
"FW-PCR-4": ["Applejack"],
"FW-PCR-5": ["Rainbow Dash"],
"FW-PCR-6": ["Rarity"],
"FW-PCR-7": ["Twilight Sparkle"],
"FW-PCR-8": ["Fluttershy"],
"FW-PCR-9": ["Pinkie Pie"],
"FW-PCR-10": ["Applejack"],
"FW-PCR-11": ["Rainbow Dash"],
"FW-PCR-12": ["Rarity"],
"FW-PRR-1": ["Twilight Sparkle"],
"FW-PRR-2": ["Fluttershy"],
"FW-PRR-3": ["Pinkie Pie"],
"FW-PRR-4": ["Applejack"],
"FW-PRR-5": ["Rainbow Dash"],
"FW-PRR-6": ["Rarity"],


/// DISCORD TCG ///

"BP02-C01": ["Twilight Sparkle"],
"BP02-C02": ["Twilight Sparkle"],
"BP02-C03": ["Fluttershy"],
"BP02-C04": ["Fluttershy"],
"BP02-C05": ["Pinkie Pie"],
"BP02-C06": ["Pinkie Pie"],
"BP02-C07": ["Applejack"],
"BP02-C08": ["Applejack"],
"BP02-C09": ["Rainbow Dash"],
"BP02-C10": ["Rainbow Dash"],
"BP02-C11": ["Rarity"],
"BP02-C12": ["Rarity"],
"BP02-C13": ["Spike"],
"BP02-C14": ["Spike"],
"BP02-C15": ["Apple Bloom"],
"BP02-C16": ["Sweetie Belle"],
"BP02-C17": ["Scootaloo"],
"BP02-C18": ["Discord"],
"BP02-C19": ["Zecora"],
"BP02-C20": ["Granny Smith"],
"BP02-C21": ["Filthy Rich"],
"BP02-C22": ["Diamond Tiara"],
"BP02-C23": ["Pound Cake"],
"BP02-C24": ["Pumpkin Cake"],
"BP02-C25": ["Twilight Sparkle, Spike"],
"BP02-C26": ["Pinkie Pie, Rainbow Dash, Fluttershy, Applejack, Rarity, Twilight Sparkle"],
"BP02-C27": ["Twilight Sparkle, Smarty Pants, Apple Bloom, Sweetie Belle, Scootaloo"],
"BP02-C28": ["Pinkie Pie, Rainbow Dash, Fluttershy, Applejack, Rarity, Twilight Sparkle, Spike"],
"BP02-C29": ["Fluttershy, Rainbow Dash"],
"BP02-C30": ["Fluttershy"],
"BP02-C31": ["Fluttershy, Rainbow Dash"],
"BP02-C32": ["Fluttershy, Caramel, White Lightning, Spring Skies"],
"BP02-C33": ["Pinkie Pie, Pound Cake, Carrot Cake, Mr. Cup Cake"],
"BP02-C34": ["Pinkie Pie, Pound Cake, Carrot Cake"],
"BP02-C35": ["Pinkie Pie, Pound Cake, Carrot Cake"],
"BP02-C36": ["Mrs. Cup Cake, Mr. Cup Cake, Pound Cake, Carrot Cake, Pinkie Pie"],
"BP02-C37": ["Applejack, Mayor Mare, Carrot Top, Lemon Hearts, Sweetie Drops, Caramel, Shoe Shine, Daisy"],
"BP02-C38": ["Rarity, Twilight Sparkle, Rainbow Dash, Applejack"],
"BP02-C39": ["Applejack"],
"BP02-C40": ["Fluttershy, Applejack, Twilight"],
"BP02-C41": ["Rainbow Dash, Fluttershy"],
"BP02-C42": ["Rainbow Dash, Tank"],
"BP02-C43": ["Rainbow Dash"],
"BP02-C44": ["Pinkie Pie, Rainbow Dash, Fluttershy, Applejack, Rarity, Twilight Sparkle, Winona, Spike, Tank, Owlowiscious, Angel, Opalescence, Gummy"],
"BP02-C45": ["Rarity, Hayseed Turnip Truck, Jet Set, Upper Crust"],
"BP02-C46": ["Rarity, Fancy Pants"],
"BP02-C47": ["Pinkie Pie, Rainbow Dash, Fluttershy, Applejack, Rarity, Twilight Sparkle"],
"BP02-C48": ["Pinkie Pie, Rainbow Dash, Fluttershy, Applejack, Rarity, Twilight Sparkle, Fancy Pants"],
"BP02-U01": ["Twilight Sparkle"],
"BP02-U02": ["Twilight Sparkle"],
"BP02-U03": ["Fluttershy"],
"BP02-U04": ["Fluttershy"],
"BP02-U05": ["Pinkie Pie"],
"BP02-U06": ["Pinkie Pie"],
"BP02-U07": ["Applejack"],
"BP02-U08": ["Rainbow Dash"],
"BP02-U09": ["Rainbow Dash"],
"BP02-U10": ["Rainbow Dash"],
"BP02-U11": ["Rarity"],
"BP02-U12": ["Rarity"],
"BP02-U13": ["Spike"],
"BP02-U14": ["Apple Bloom"],
"BP02-U15": ["Sweetie Belle"],
"BP02-U16": ["Scootaloo"],
"BP02-U17": ["Discord"],
"BP02-U18": ["Discord"],
"BP02-ER01": [""],
"BP02-ER02": [""],
"BP02-ER03": [""],
"BP02-ER04": [""],
"BP02-ER05": [""],
"BP02-ER06": [""],
"BP02-SR01": ["Twilight Sparkle"],
"BP02-SR02": ["Fluttershy"],
"BP02-SR03": ["Pinkie Pie"],
"BP02-SR04": ["Applejack"],
"BP02-SR05": ["Rainbow Dash"],
"BP02-SR06": ["Rarity"],
"BP02-SR07": ["Spike"],
"BP02-SR08": ["Discord"],
"BP02-SR09": ["Apple Bloom, Applejack"],
"BP02-SR10": ["Sweetie Belle, Rarity"],
"BP02-SR11": ["Scootaloo, Rainbow Dash"],
"BP02-SR12": ["Daring Do"],
"BP02-SR13": ["Philomena"],
"BP02-SR14": ["Big McIntosh"],
"BP02-SPR01": ["Twilight Sparkle, Spike"],
"BP02-SPR02": ["Spike"],
"BP02-SPR03": ["Twilight Sparkle"],
"BP02-SPR04": ["Fluttershy"],
"BP02-SPR05": ["Fluttershy, Angel"],
"BP02-SPR06": ["Pinkie Pie"],
"BP02-SPR07": ["Pinkie Pie, Apple Bloom"],
"BP02-SPR08": ["Applejack"],
"BP02-SPR09": ["Big McIntosh, Applejack, Apple Bloom"],
"BP02-SPR10": ["Rainbow Dash"],
"BP02-SPR11": ["Rainbow Dash"],
"BP02-SPR12": ["Rarity, Opalescence"],
"BP02-SPR13": ["Rarity, Sweetie Belle, Opalescence"],
"BP02-SPR14": ["Apple Bloom"],
"BP02-SPR15": ["Sweetie Belle"],
"BP02-SPR16": ["Snips, Scootaloo"],
"BP02-SPR17": ["Cheerilee, Snips, Snails, Diamond Tiara, Silver Spoon, Sweetie Belle, Scootaloo, Apple Bloom, Twist"],
"BP02-SPR18": ["Pinkie Pie, Twilight Sparkle, Rarity, Fluttershy, Applejack, Opalescence, Angel, Winona, Gummy, Owlowiscious "],
"BP02-SPR19": ["Granny Smith"],
"BP02-SPR20": ["Pinkie Pie, Fluttershy, Applejack, Rainbow Dash"],
"BP02-SPR21": ["Daring Do"],
"BP02-SPR22": ["Smarty Pants"],
"BP02-SPR23": ["Daring Do"],
"BP02-SPR24": ["Pinkie Pie"],
"BP02-SPR25": [""],
"BP02-SPR26": ["Spike"],
"BP02-SPR27": [""],
"BP02-SPR28": [""],
"BP02-GR01": [""],
"BP02-GR02": ["Twilight Sparkle, Spike, Daring Do"],
"BP02-GR03": ["Fluttershy, Daring Do"],
"BP02-GR04": ["Applejack, Daring Do"],
"BP02-GR05": ["Rainbow Dash, Daring Do"],
"BP02-GR06": ["Rarity, Daring Do"],
"BP02-GR07": ["Twilight Sparkle, Spike"],
"BP02-GR08": ["Fluttershy"],
"BP02-GR09": ["Pinkie Pie"],
"BP02-GR10": ["Applejack"],
"BP02-GR11": ["Rainbow Dash"],
"BP02-GR12": ["Rarity"],
"BP02-CR01": ["Twilight Sparkle, Spike"],
"BP02-CR02": ["Fluttershy, Dragon Lord"],
"BP02-CR03": ["Pinkie Pie"],
"BP02-CR04": ["Applejack, Winona"],
"BP02-CR05": ["Rainbow Dash"],
"BP02-CR06": ["Rarity"],
"BP02-CR07": ["Twilight Sparkle, Spike, Discord"],
"BP02-CR08": ["Fluttershy, Discord"],
"BP02-CR09": ["Pinkie Pie, Discord"],
"BP02-CR10": ["Applejack, Discord"],
"BP02-CR11": ["Rainbow Dash, Discord"],
"BP02-CR12": ["Rarity, Discord"],
"BP02-RR01": ["Twilight Sparkle"],
"BP02-RR02": ["Fluttershy"],
"BP02-RR03": ["Pinkie Pie"],
"BP02-RR04": ["Applejack"],
"BP02-RR05": ["Rainbow Dash"],
"BP02-RR06": ["Rarity"],
"BP02-PER01-A2": [""],
"BP02-PER01-B2": [""],
"BP02-PER02-A2": [""],
"BP02-PER02-B2": [""],
"BP02-PER03-A2": [""],
"BP02-PER03-B2": [""],
"BP02-PER04-A2": [""],
"BP02-PER04-B2": [""],
"BP02-PER05-A2": [""],
"BP02-PER05-B2": [""],
"BP02-PER06-A2": [""],
"BP02-PER06-B2": [""],
"BP02-PGR01": ["Twilight Sparkle, Spike, Daring Do"],
"BP02-PGR02": ["Fluttershy, Daring Do"],
"BP02-PGR03": ["Pinkie Pie, Daring Do"],
"BP02-PGR04": ["Applejack, Daring Do"],
"BP02-PGR05": ["Rainbow Dash, Daring Do"],
"BP02-PGR06": ["Rarity, Daring Do"],
"BP02-PSPR01": ["Spike"],
"BP02-PSPR02": ["Spike"],
"BP02-PSPR03": ["Fluttershy"],
"BP02-PSPR04": ["Rainbow Dash"],
"BP02-PSPR05": ["Applejack, Apple Bloom"],
"BP02-PSPR06": ["Rarity, Sweetie Belle"],
"BP02-PSPR07": ["Rainbow Dash, Scootaloo, Snips"],
"BP02-PSPR08": ["Winona, Owlowiscious, Tank, Gummy, Opalescence, Angel"],
"BP02-PSPR09": ["Daring Do"],
"BP02-PSPR10": [""],
"BP02-PSPR11": [""],
"BP02-PCR01": ["Twilight Sparkle, Spike"],
"BP02-PCR02": ["Fluttershy"],
"BP02-PCR03": ["Pinkie Pie"],
"BP02-PCR04": ["Applejack, Winona"],
"BP02-PCR05": ["Rainbow Dash"],
"BP02-PCR06": ["Rarity, Fruit Bat"],
"BP02-PCR07": ["Twilight Sparkle, Spike, Discord"],
"BP02-PCR08": ["Fluttershy, Angel, Discord"],
"BP02-PCR09": ["Pinkie Pie, Discord"],
"BP02-PCR10": ["Applejack, Discord"],
"BP02-PCR11": ["Rainbow Dash, Discord"],
"BP02-PCR12": ["Rarity, Discord"],
"BP02-PRR01": ["Twilight Sparkle, Discord"],
"BP02-PRR02": ["Fluttershy, Discord"],
"BP02-PRR03": ["Pinkie Pie, Discord"],
"BP02-PRR04": ["Applejack, Discord"],
"BP02-PRR05": ["Rainbow Dash, Discord"],
"BP02-PRR06": ["Rarity, Discord"],

};