export const starCharacterMap: Record<string, string[]> = {

  /// STAR ONE ///

  "4-SSR-1": ["Twilight Sparkle"],
  "4-SSR-2": ["Pinkie Pie"],
  "4-SSR-3": ["Rainbow Dash"],
  "4-SSR-4": ["Rarity"],
  "4-SSR-5": ["Fluttershy"],
  "4-SSR-6": ["Applejack"],
  "4-SSR-7": ["Spike"],
  "4-SSR-8": ["Apple Bloom"],
  "4-SSR-9": ["Scootaloo"],
  "4-SSR-10": ["Sweetie Belle"],
  "4-SSR-11": ["Princess Amore"],
  "4-SSR-12": ["Diamond Tiara"],
  "4-SSR-13": ["Granny Smith"],
  "4-SSR-14": ["Sugar Belle"],
  "4-SSR-15": ["Big McIntosh"],
  "4-SSR-16": ["Junebug"],
  "4-SSR-17": ["Bright Mac"],
  "4-SSR-18": ["Aunt Orange"],
  "4-SSR-19": ["Pumpkin Cake"],
  "4-SSR-20": ["Pound Cake"],
  "4-SCR-1": ["Princess Twilight Sparkle"],
  "4-SCR-2": ["Pinkie Pie"],
  "4-SCR-3": ["Rainbow Dash"],
  "4-SCR-4": ["Rarity"],
  "4-SCR-5": ["Fluttershy"],
  "4-SCR-6": ["Applejack"],
  "4-SCR-7": ["Starlight Glimmer"],
  "4-SCR-8": ["Princess Celestia"],
  "4-SCR-9": ["Princess Luna"],
  "4-SCR-10": ["Princess Cadance"],
  "4-SCR-11": ["Shining Armor"],
  "4-SCR-12": ["Sunburst"],
  "4-SCR-13": ["Cherry Jubilee"],
  "4-SCR-14": ["Maud Pie"],
  "4-SCR-15": ["Countess Coloratura"],
  "4-SCR-16": ["Aunt Orange"],
  "4-SCR-17": ["Coco Pommel"],
  "4-SCR-18": ["Discord"],
  "4-UR-1": ["Princess Twilight Sparkle"],
  "4-UR-2": ["Pinkie Pie"],
  "4-UR-3": ["Rainbow Dash"],
  "4-UR-4": ["Fluttershy"],
  "4-UR-5": ["Rarity"],
  "4-UR-6": ["Applejack"],
  "4-UR-7": ["Spike"],
  "4-UR-8": ["Princess Celestia"],
  "4-UR-9": ["Princess Luna"],
  "4-UR-10": ["Starlight Glimmer"],
  "4-UR-11": ["Princess Cadance"],
  "4-UR-12": ["Nightmare Moon"],
  "4-UR-13": ["Mistmane"],
  "4-UR-14": ["Vapor Trail"],
  "4-UR-15": ["Pear Butter"],
  "4-UR-16": ["Spitfire"],
  "4-UR-17": ["Photo Finish"],
  "4-UR-18": ["Flurry Heart"],
  "4-USR-1": ["Starlight Glimmer, Twilight Sparkle, Yuri"],
  "4-USR-2": ["Twilight Sparkle"],
  "4-USR-3": ["Applejack, Pinkie Pie, Rarity, Twilight Sparkle, Rainbow Dash, Fluttershy"],
  "4-USR-4": ["Princess Celestia"],
  "4-USR-5": ["Princess Luna"],
  "4-USR-6": ["Princess Celestia, Princess Luna"],
  "4-USR-7": ["Rarity"],
  "4-USR-8": ["Pinkie Pie"],
  "4-USR-9": ["Fluttershy"],
  "4-USR-10": ["Rainbow Dash"],
  "4-USR-11": ["Applejack"],
  "4-USR-12": ["Starlight Glimmer"],
  "4-USR-13": ["Princess Celestia, Starlight Glimmer"],
  "4-USR-14": ["Applejack, Pinkie Pie, Rarity, Twilight Sparkle, Rainbow Dash, Fluttershy, Ponyamory"],
  "4-USR-15": ["Twilight Sparkle"],
  "4-AR-1": ["Princess Twilight Sparkle, Owlowiscious"],
  "4-AR-2": ["Pinkie Pie, Gummy"],
  "4-AR-3": ["Rainbow Dash, Tank"],
  "4-AR-4": ["Rarity, Opalescence"],
  "4-AR-5": ["Fluttershy, Angel"],
  "4-AR-6": ["Applejack, Winona"],
  "4-AR-7": ["Starlight Glimmer"],
  "4-AR-8": ["Sunset Shimmer"],
  "4-AR-9": ["Nightmare Moon"],
  "4-OR-1": ["Twilight Sparkle"],
  "4-OR-2": ["Pinkie Pie"],
  "4-OR-3": ["Rainbow Dash"],
  "4-OR-4": ["Rarity"],
  "4-OR-5": ["Fluttershy"],
  "4-OR-6": ["Applejack"],
  "4-OR-7": ["Princess Luna"],
  "4-BP-1": ["Twilight Sparkle"],
  "4-BP-2": ["Pinkie Pie"],
  "4-BP-3": ["Rainbow Dash"],
  "4-BP-4": ["Rarity"],
  "4-BP-5": ["Fluttershy"],
  "4-BP-6": ["Applejack"],
  "4-BP-7": ["Princess Celestia"],
  "4-BP-8": ["Princess Luna"],
  "4-BP-9": ["Trixie"],
  "4-SAR-1": ["Princess Twilight Sparkle"],
  "4-SAR-2": ["Pinkie Pie"],
  "4-SAR-3": ["Rainbow Dash"],
  "4-SAR-4": ["Rarity"],
  "4-SAR-5": ["Fluttershy"],
  "4-SAR-6": ["Applejack"],
  "4-SAR-7": ["Starlight Glimmer"],
  "4-SAR-8": ["Sunset Shimmer"],
  "4-SAR-9": ["Nightmare Moon"],

};