export const promoCharacterMap: Record<string, string[]> = {
  // CCG Promos
  "9-PR-1": ["Princess Twilight Sparkle"],
  "9-PR-2": ["Twilight Sparkle, Rarity, Pinkie Pie, Applejack, Rainbow Dash, Fluttershy"],
  "9-PR-3": ["Twilight Sparkle, Rarity, Pinkie Pie, Applejack, Rainbow Dash, Fluttershy, Spike"],
  "9-PR-4": ["Twilight Sparkle, Rarity, Pinkie Pie, Applejack, Rainbow Dash, Fluttershy"],
  "9-PR-5": ["Princess Twilight Sparkle"],
  "9-PR-7": ["Twilight Sparkle, Fluttershy, Rainbow Dash"],
  "9-PR-8": ["Twilight Sparkle, Owlowiscious, Spike, Princess Celestia"],
  "9-PR-9": ["Applejack, DJ-Pon3, Winona"],
  "9-PR-10": ["Pinkie Pie, Gummy, Zecora"],
  "9-PR-11": ["Rainbow Dash, Apple Bloom, Tank"],
  "9-PR-12": ["Fluttershy, Sweetie Belle, Angel"],
  "9-PR-13": ["Rarity, Scootaloo, Princess Luna, Opalescence"],

  // TCG Promos
  "tcgpromos-RR01": ["Princess Twilight Sparkle"],
  "tcgpromos-RR02": ["Fluttershy"],
  "tcgpromos-RR03": ["Pinkie Pie"],
  "tcgpromos-RR04": ["Applejack"],
  "tcgpromos-RR05": ["Rainbow Dash"],
  "tcgpromos-RR06": ["Rarity"],
  "tcgpromos-RR07": ["Twilight Sparkle"],
  "tcgpromos-RR08": ["Fluttershy, Angel"],
  "tcgpromos-RR09": ["Pinkie Pie"],
  "tcgpromos-RR10": ["Applejack"],
  "tcgpromos-RR11": ["Rainbow Dash"],
  "tcgpromos-RR12": ["Rarity"],
  "tcgpromos-RR13": ["Twilight Sparkle"],
  "tcgpromos-RR14": ["Fluttershy, Angel"],
  "tcgpromos-RR15": ["Pinkie Pie"],
  "tcgpromos-RR16": ["Applejack"],
  "tcgpromos-RR17": ["Rainbow Dash"],
  "tcgpromos-RR18": ["Rarity"],
};