export const moonCharacterMap: Record<string, string[]> = {
  "1-R-1": ["Princess Twilight Sparkle"],
  "1-R-2": ["Pinkie Pie"],
  "1-R-3": ["Rainbow Dash"],
  "1-R-4": ["Rarity"],
  "1-R-5": ["Fluttershy"],
  "1-R-6": ["Applejack"],
  "1-R-7": ["Spike"],
  "1-R-8": ["Cheese Sandwich"],
  "1-R-9": ["Cheerilee"],
  "1-R-10": ["Babs Seed"],
  "1-R-11": ["Diamond Tiara"],
  "1-R-12": ["Silver Spoon"],
  "1-R-13": ["Starlight Glimmer"],
  "1-R-14": ["Trixie"],
  "1-R-15": ["Lyra Heartstrings"],
  "1-R-16": ["Sweetie Drops"],
  "1-R-17": ["Muffins"],
  "1-R-18": ["Lily Valley"],
  "1-R-19": ["Daisy"],
  "1-R-20": ["Junebug"],
  "1-R-21": ["Ms. Harshwinny"],
  "1-R-22": ["Peachbottom"],
  "1-R-23": ["Suri Polomare"],
  "1-R-24": ["Zipporwhill"],
  "1-R-25": ["Dr. Caballeron"],
  "1-R-26": ["Stygian"],
  "1-R-27": ["Zecora"],
  "1-R-28": ["Discord"],
  "1-R-29": ["Iron Will"],
  "1-R-30": ["Fruit Bat"],
  "1-SR-1": ["Princess Twilight Sparkle"],
  "1-SR-2": ["Pinkie Pie"],
  "1-SR-3": ["Rainbow Dash"],
  "1-SR-4": ["Rarity"],
  "1-SR-5": ["Fluttershy"],
  "1-SR-6": ["Applejack"],
  "1-SR-7": ["Princess Twilight Sparkle"],
  "1-SR-8": ["Pinkie Pie"],
  "1-SR-9": ["Rainbow Dash"],
  "1-SR-10": ["Rarity"],
  "1-SR-11": ["Fluttershy"],
  "1-SR-12": ["Applejack"],
  "1-SR-13": ["Sunburst"],
  "1-SR-14": ["Starlight Glimmer"],
  "1-SR-15": ["Big McIntosh"],
  "1-SR-16": ["Maud Pie"],
  "1-SR-17": ["Spitfire"],
  "1-SR-18": ["Flurry Heart"],
  "1-SR-19": ["Pizzelle"],
  "1-SR-20": ["Steven Magnet"],
    ...Object.fromEntries(
    Array.from({ length: 52 }, (_, i) => {
      const names = [
        "Princess Twilight Sparkle",
        "Pinkie Pie",
        "Fluttershy",
        "Rainbow Dash",
        "Rarity",
        "Applejack",
        "Spike",
        "Pear Butter",
        "Nurse RedHeart",
        "Cherry Jubilee",
        "Starlight Glimmer",
        "Trixie",
        "Sunset Shimmer",
      ];

      return [
        `1-SSR-${i + 1}`,
        [names[i % names.length]],
      ];
    })
  ),

  "1-SSR-53": ["Princess Luna"],
  "1-SSR-54": ["Princess Celestia"],
  "1-HR-1": ["Princess Twilight Sparkle, Rainbow Dash, Pinkie Pie, Applejack, Fluttershy, Rarity, Spike"],
  "1-HR-2": ["Princess Twilight Sparkle, Rainbow Dash, Pinkie Pie, Applejack, Fluttershy, Rarity"],
  "1-HR-3": ["Princess Twilight Sparkle, Pinkie Pie, Rainbow Dash"],
  "1-HR-4": ["Princess Twilight Sparkle, Rainbow Dash, Pinkie Pie, Applejack, Fluttershy, Rarity"],
  "1-HR-5": ["Applejack, Apple Bloom, Spike"],
  "1-HR-6": ["Princess Twilight Sparkle, Sweetie Drops"],
  "1-HR-7": ["Rarity"],
  "1-HR-8": ["Fluttershy"],
  "1-HR-9": ["Pinkie Pie"],
  "1-HR-10": ["Rainbow Dash"],
  "1-HR-11": ["Princess Celesita, Princess Luna"],
  "1-HR-12": ["Apple Bloom, Sweetie Belle, Spike, Scootaloo, Applejack"],
  "1-HR-13": ["Princess Luna, Applejack, Sweetie Belle, Scootaloo, Apple Bloom, Spike"],
  "1-HR-14": ["Princess Luna, Applejack"],
  "1-HR-15": ["Princess Twilight Sparkle"],
  "1-HR-16": ["Princess Twilight Sparkle, Bulk Biceps"],
  "1-HR-17": ["Sweetie Belle, Scootaloo, Apple Bloom, Fluttershy"],
  "1-HR-18": ["Sweetie Belle, Scootaloo, Apple Bloom, Fluttershy, Zecora"],
  "1-HR-19": ["Princess Luna, Spike, Apple Bloom, Sweetie Belle, Scootaloo"],
  "1-HR-20": ["Rarity, Princess Luna"],
  "1-HR-21": ["Rarity, Princess Luna"],
  "1-HR-22": ["Pinkie Pie, Granny Smith"],
  "1-HR-23": ["Fluttershy"],
  "1-HR-24": ["Pinkie Pie, Princess Luna, Scootaloo, Nightmare Moon"],
  "1-HR-25": ["Nightmare Moon"],
  "1-HR-26": ["Nightmare Moon, Pinkie Pie, Scootaloo, Apple Bloom, Sweetie Belle"],
  "1-HR-27": ["Zecora, Pinkie Pie, Sweetie Belle, Scootaloo, Apple Bloom, Spike"],
  "1-HR-28": ["Applejack, Apple Bloom, Scootaloo, Sweetie Belle"],
  "1-HR-29": ["Rainbow Dash, Pinkie Pie"],
  "1-HR-30": ["Rainbow Dash, Fluttershy"],
  "1-HR-31": ["Princess Twilight Sparkle, Nightmare Moon, Rarity"],
  "1-HR-32": ["Princess Twilight Sparkle, Nightmare Moon"],
  "1-HR-33": ["Princess Twilight Sparkle, Rarity, Pinkie Pie, Apple Bloom, Sweetie Belle, Scootaloo, Pinkie Pie, Fluttershy, Applejack"],
  "1-HR-34": ["Applejack, Pinkie Pie, Apple Bloom, Sweetie Belle, Scootaloo, Rarity, Princess Twilight Sparkle, Fluttershy, Rainbow Dash"],
  "1-HR-35": ["Zecora, Rarity, Pinkie Pie, Princess Twilight Sparkle, Applejack, Fluttershy, Rainbow Dash, Princess Luna"],
  "1-HR-36": ["Fluttershy, Rarity, Princess Luna, Zecora, Pinkie Pie, Spike, Princess Twilight Sparkle"],
  "1-UR-1": ["Princess Twilight Sparkle"],
  "1-UR-2": ["Pinkie Pie"],
  "1-UR-3": ["Rainbow Dash"],
  "1-UR-4": ["Fluttershy"],
  "1-UR-5": ["Rarity"],
  "1-UR-6": ["Applejack"],
  "1-UR-7": ["DJ Pon-3"],
  "1-UR-8": ["Octavia"],
  "1-UR-9": ["Cheerilee"],
  "1-UR-10": ["Sweetie Belle"],
  "1-UR-11": ["Scootaloo"],
  "1-UR-12": ["Apple Bloom"],
  "1-UR-13": ["Songbird Serenade"],
  "1-UR-14": ["Cheese Sandwich"],
  "1-UR-15": ["Countess Coloratura"],
  "1-UR-16": ["Applejack (Hidden)"],
  "1-LSR-1": ["Princess Twilight Sparkle"],
  "1-LSR-2": ["Pinkie Pie"],
  "1-LSR-3": ["Rainbow Dash"],
  "1-LSR-4": ["Fluttershy"],
  "1-LSR-5": ["Rarity"],
  "1-LSR-6": ["Applejack"],
  "1-LSR-7": ["Star Swirl"],
  "1-LSR-8": ["Somnambula"],
  "1-LSR-9": ["Flash Magnus"],
  "1-LSR-10": ["Mage Meadowbrooke"],
  "1-LSR-11": ["Mistmane"],
  "1-LSR-12": ["Rockhoof"],
  "1-LSR-13": ["Starlight Glimmer"],
  "1-LSR-14": ["Trixie"],
  "1-LSR-15": ["Sunburst"],
  "1-SGR-1": ["Princess Twilight Sparkle"],
  "1-SGR-2": ["Pinkie Pie"],
  "1-SGR-3": ["Rainbow Dash"],
  "1-SGR-4": ["Rarity"],
  "1-SGR-5": ["Fluttershy"],
  "1-SGR-6": ["Applejack"],
  "1-SGR-7": ["Princess Cadance"],
  "1-SGR-8": ["Flurry Heart"],
  "1-SC-1": ["Princess Twilight Sparkle"],
  "1-SC-2": ["Pinkie Pie"],
  "1-SC-3": ["Rainbow Dash"],
  "1-SC-4": ["Rarity"],
  "1-SC-5": ["Fluttershy"],
  "1-SC-6": ["Applejack"],
  "1-SC-7": ["Princess Twilight Sparkle, Rarity, Applejack, Pinkie Pie, Fluttershy, Rainbow Dash, Hidden"],



    "2-R-1": ["Princess Twilight Sparkle"],
  "2-R-2": ["Pinkie Pie"],
  "2-R-3": ["Rainbow Dash"],
  "2-R-4": ["Rarity"],
  "2-R-5": ["Fluttershy"],
  "2-R-6": ["Applejack"],
  "2-R-7": ["Nurse RedHeart"],
  "2-R-8": ["Cozy Glow"],
  "2-R-9": ["Toola Roola"],
  "2-R-10": ["Coconut Cream"],
  "2-R-11": ["Inky Rose"],
  "2-R-12": ["Prince BlueBlood"],
  "2-R-13": ["Sunny Daze"],
  "2-R-14": ["Peachy Pie"],
  "2-R-15": ["Bulk Biceps"],
  "2-R-16": ["Randolph"],
  "2-R-17": ["Fleur De Lis"],
  "2-R-18": ["Trouble Shoes"],
  "2-R-19": ["Mr. Stripes"],
  "2-R-20": ["Plaid Stripes"],
  "2-R-21": ["Night Glider"],
  "2-R-22": ["Party Favor"],
  "2-R-23": ["Double Diamond"],
  "2-R-24": ["Snips"],
  "2-R-25": ["Snails"],
  "2-R-26": ["Gabriella"],
  "2-R-27": ["Seabreeze"],
  "2-R-28": ["Parasprite"],
  "2-R-29": ["Cockatrice"],
  "2-R-30": ["Jackalope"],
    "2-SR-1": ["Princess Twilight Sparkle"],
  "2-SR-2": ["Pinkie Pie"],
  "2-SR-3": ["Rainbow Dash"],
  "2-SR-4": ["Fluttershy"],
  "2-SR-5": ["Rarity"],
  "2-SR-6": ["Applejack"],
  "2-SR-7": ["Princess Twilight Sparkle"],
  "2-SR-8": ["Pinkie Pie"],
  "2-SR-9": ["Rainbow Dash"],
  "2-SR-10": ["Fluttershy"],
  "2-SR-11": ["Rarity"],
  "2-SR-12": ["Applejack"],
  "2-SR-13": ["Apple Bloom"],
  "2-SR-14": ["Scootaloo"],
  "2-SR-15": ["Sweetie Belle"],
  "2-SR-16": ["Octavia"],
  "2-SR-17": ["Moon Dancer"],
  "2-SR-18": ["Twinkleshine"],
  "2-SR-19": ["Lemon Hearts"],
  "2-SR-20": ["Minuette"],
    ...Object.fromEntries(
    Array.from({ length: 52 }, (_, i) => {
      const names = [
        "Princess Twilight Sparkle",
        "Pinkie Pie",
        "Fluttershy",
        "Rainbow Dash",
        "Rarity",
        "Applejack",
        "Spike",
        "Apple Bloom",
        "Scootaloo",
        "Sweetie Belle",
        "Vapor Trail",
        "Flurry Heart",
        "Princess Cadance",
      ];

      return [
        `2-SSR-${i + 1}`,
        [names[i % names.length]],
      ];
    })
  ),

  "2-SSR-53": ["Queen Chrysalis"],
  "2-SSR-54": ["Discord"],
    "2-HR-1": ["Princess Twilight Sparkle"],
  "2-HR-2": ["Pinkie Pie"],
  "2-HR-3": ["Rainbow Dash"],
  "2-HR-4": ["Rarity"],
  "2-HR-5": ["Fluttershy"],
  "2-HR-6": ["Applejack"],
  "2-HR-7": ["Spike"],
  "2-HR-8": ["Granny Smith"],
  "2-HR-9": ["Sweetie Belle"],
  "2-HR-10": ["Rarity, Fluttershy, Pinkie Pie, Rainbow Dash"],
  "2-HR-11": ["Pinkie Pie, Maud Pie"],
  "2-HR-12": ["Rainbow Dash"],
  "2-HR-13": ["Applejack, Rarity"],
  "2-HR-14": ["Rarity, Princess Twilight Sparkle"],
  "2-HR-15": ["Princess Twilight Sparkle, Pinkie Pie, Spike"],
  "2-HR-16": ["Scootaloo, Sweetie Belle, Applebloom"],
  "2-HR-17": ["Scootaloo, Sweetie Belle, Applebloom"],
  "2-HR-18": ["Rainbow Dash, Little Strongheart"],
  "2-HR-19": ["Fluttershy, Princess Twilight Sparkle"],
  "2-HR-20": ["Rainbow Dash, Pinkie Pie"],
  "2-HR-21": ["Starlight Glimmer, Trixie"],
  "2-HR-22": ["Pinkie Pie, Rarity, Princess Twilight Sparkle"],
  "2-HR-23": ["Princess Twilight Sparkle"],
  "2-HR-24": ["Pinkie Pie"],
  "2-HR-25": ["Fluttershy"],
  "2-HR-26": ["Rainbow Dash"],
  "2-HR-27": ["Applejack"],
  "2-HR-28": ["Rarity"],
  "2-HR-29": ["Spike"],
  "2-HR-30": ["Princess Celestia"],
  "2-UR-1": ["Princess Twilight Sparkle"],
  "2-UR-2": ["Pinkie Pie"],
  "2-UR-3": ["Rainbow Dash"],
  "2-UR-4": ["Fluttershy"],
  "2-UR-5": ["Rarity"],
  "2-UR-6": ["Applejack"],
  "2-UR-7": ["Spitfire"],
  "2-UR-8": ["Fleetfoot"],
  "2-UR-9": ["Thunderlane"],
  "2-UR-10": ["Vapor Trail"],
  "2-UR-11": ["Maud Pie"],
  "2-UR-12": ["Trixie"],
  "2-UR-13": ["Starlight Glimmer"],
  "2-UR-14": ["Princess Luna"],
  "2-UR-15": ["Princess Cadance"],
  "2-UR-16": ["Rainbow Dash, Hidden"],
    "2-LSR-1": ["Princess Twilight Sparkle, Owlowiscious"],
  "2-LSR-2": ["Pinkie Pie, Gummy"],
  "2-LSR-3": ["Rainbow Dash, Tank"],
  "2-LSR-4": ["Fluttershy, Angel"],
  "2-LSR-5": ["Rarity, Opalescence"],
  "2-LSR-6": ["Applejack, Winona"],
  "2-LSR-7": ["Princess Celestia, Philomena"],
  "2-LSR-8": ["Princess Luna, Tiberius"],
  "2-LSR-9": ["Apple Bloom"],
  "2-LSR-10": ["Scootaloo"],
  "2-LSR-11": ["Sweetie Belle"],
  "2-LSR-12": ["Sunset Shimmer, Ray"],
  "2-LSR-13": ["Spike, Philomena"],
  "2-LSR-14": ["Shining Armor"],
  "2-LSR-15": ["Maud Pie, Rock"],
  "2-LSR-16": ["Cheese Sandwich, Boneless"],
  "2-SGR-1": ["Princess Twilight Sparkle"],
  "2-SGR-2": ["Pinkie Pie"],
  "2-SGR-3": ["Rainbow Dash"],
  "2-SGR-4": ["Rarity"],
  "2-SGR-5": ["Fluttershy"],
  "2-SGR-6": ["Applejack"],
  "2-SGR-7": ["Spike"],
  "2-SGR-8": ["Princess Celestia"],
    "2-ZR-1": ["Princess Twilight Sparkle"],
  "2-ZR-2": ["Pinkie Pie"],
  "2-ZR-3": ["Rainbow Dash"],
  "2-ZR-4": ["Rarity"],
  "2-ZR-5": ["Fluttershy"],
  "2-ZR-6": ["Applejack"],
  "2-ZR-7": ["Princess Twilight Sparkle, Pinkie Pie, Rainbow Dash, Rarity, Applejack, Spike, Fluttershy"],
    "2-SC-1": ["Princess Twilight Sparkle"],
  "2-SC-2": ["Pinkie Pie"],
  "2-SC-3": ["Rainbow Dash"],
  "2-SC-4": ["Rarity"],
  "2-SC-5": ["Fluttershy"],
  "2-SC-6": ["Applejack"],
  "2-SC-7": ["Princess Twilight Sparkle"],
  "2-SHINING ZR-1": ["Princess Twiligiht Sparkle, Rarity, Rainbow Dash, Fluttershy, Applejack, Pinkie Pie"],

    "3-R-1": ["Princess Twilight Sparkle"],
  "3-R-2": ["Pinkie Pie"],
  "3-R-3": ["Rainbow Dash"],
  "3-R-4": ["Rarity"],
  "3-R-5": ["Fluttershy"],
  "3-R-6": ["Applejack"],
  "3-R-7": ["Spike"],
  "3-R-8": ["Prim Hemline"],
  "3-R-9": ["Hoity Toity"],
  "3-R-10": ["Photo Finish"],
  "3-R-11": ["Sapphire Shores"],
  "3-R-12": ["Fancy Pants"],
  "3-R-13": ["Svengallop"],
  "3-R-14": ["Tree Hugger"],
  "3-R-15": ["Sassy Saddles"],
  "3-R-16": ["Night Light"],
  "3-R-17": ["Twilight Velvet"],
  "3-R-18": ["Zephyr Breeze"],
  "3-R-19": ["Twist"],
  "3-R-20": ["Pipsqueak"],
  "3-R-21": ["Sky Stinger"],
  "3-R-22": ["Vapor Trail"],
  "3-R-23": ["Lord Tirek"],
  "3-R-24": ["King Sombra"],
  "3-R-25": ["Smooze"],
  "3-R-26": ["Prince Rutherford"],
  "3-R-27": ["Little Strongheart"],
  "3-R-28": ["Manticore"],
  "3-R-29": ["Pigasus"],
  "3-R-30": ["Hydra"], 
  "3-R-31": ["Princess Twilight Sparkle"],
  "3-R-32": ["Pinkie Pie"],
  "3-R-33": ["Rainbow Dash"],
  "3-R-34": ["Rarity"],
  "3-R-35": ["Fluttershy"],
  "3-R-36": ["Applejack"],
  "3-R-37": ["Spike"],
  "3-R-38": ["Maud Pie"],
  "3-R-39": ["Limestone Pie"],
  "3-R-40": ["Marble Pie"],
  "3-R-41": ["Igneous Rock Pie"],
  "3-R-42": ["Cloudy Quartz"],
  "3-R-43": ["Apple Bloom"],
  "3-R-44": ["Big McIntosh"],
  "3-R-45": ["Granny Smith"],
  "3-R-46": ["Lyra Heartstrings"],
  "3-R-47": ["Sweetie Drops"],
  "3-R-48": ["Muffins"],
  "3-R-49": ["Doctor Whooves"],
  "3-R-50": ["Sandbar"],
  "3-R-51": ["Gallus"],
  "3-R-52": ["Smolder"],
  "3-R-53": ["Yona"],
  "3-R-54": ["Ocellus"],
  "3-R-55": ["Silverstream"],
  "3-R-56": ["Ember"],
  "3-R-57": ["Sphinx"],
  "3-R-58": ["Tri-Horned Bunyip"],
  "3-R-59": ["Bloofy"],
  "3-R-60": ["Puckwudgie"],
    "3-SR-1": ["Princess Twilight Sparkle"],
  "3-SR-2": ["Princess Twilight Sparkle"],
  "3-SR-3": ["Pinkie Pie"],
  "3-SR-4": ["Pinkie Pie"],
  "3-SR-5": ["Rainbow Dash"],
  "3-SR-6": ["Rainbow Dash"],
  "3-SR-7": ["Fluttershy"],
  "3-SR-8": ["Fluttershy"],
  "3-SR-9": ["Rarity"],
  "3-SR-10": ["Rarity"],
  "3-SR-11": ["Applejack"],
  "3-SR-12": ["Applejack"],
  "3-SR-13": ["Spike"],
  "3-SR-14": ["Muffins"],
  "3-SR-15": ["Mayor Mare"],
  "3-SR-16": ["Sweetie Belle"],
  "3-SR-17": ["Princess Luna"],
  "3-SR-18": ["Fluttershy, Discord, FlutterCord"],
  "3-SR-19": ["Spitfire"],
  "3-SR-20": ["Babs Seed"],
  "3-SR-21": ["Princess Twilight Sparkle"],
  "3-SR-22": ["Pinkie Pie"],
  "3-SR-23": ["Rainbow Dash"],
  "3-SR-24": ["Fluttershy"],
  "3-SR-25": ["Rarity"],
  "3-SR-26": ["Applejack"],
  "3-SR-27": ["Princess Twilight Sparkle"],
  "3-SR-28": ["Pinkie Pie"],
  "3-SR-29": ["Rainbow Dash"],
  "3-SR-30": ["Fluttershy"],
  "3-SR-31": ["Rarity"],
  "3-SR-32": ["Applejack"],
  "3-SR-33": ["Starlight Glimmer"],
  "3-SR-34": ["Zecora"],
  "3-SR-35": ["Apple Bloom"],
  "3-SR-36": ["Sweetie Belle"],
  "3-SR-37": ["Scootaloo"],
  "3-SR-38": ["Calamity Mane"],
  "3-SR-39": ["Princess Celestia"],
  "3-SR-40": ["Princess Cadance"],
    "3-SSR-1": ["Princess Twilight Sparkle"],
  "3-SSR-2": ["Pinkie Pie"],
  "3-SSR-3": ["Rainbow Dash"],
  "3-SSR-4": ["Rarity"],
  "3-SSR-5": ["Fluttershy"],
  "3-SSR-6": ["Applejack"],
  "3-SSR-7": ["Princess Twilight Sparkle"],
  "3-SSR-8": ["Pinkie Pie"],
  "3-SSR-9": ["Rainbow Dash"],
  "3-SSR-10": ["Rarity"],
  "3-SSR-11": ["Fluttershy"],
  "3-SSR-12": ["Applejack"],
  "3-SSR-13": ["Spike"],
  "3-SSR-14": ["Starlight Glimmer"],
  "3-SSR-15": ["Maud Pie"],
  "3-SSR-16": ["Apple Bloom"],
  "3-SSR-17": ["Granny Smith"],
  "3-SSR-18": ["Zecora"],
  "3-SSR-19": ["Mrs. Cup Cake"],
  "3-SSR-20": ["Mr. Carrot Cake"],
  "3-SSR-21": ["Princess Twilight Sparkle"],
  "3-SSR-22": ["Pinkie Pie"],
  "3-SSR-23": ["Rainbow Dash"],
  "3-SSR-24": ["Rarity"],
  "3-SSR-25": ["Fluttershy"],
  "3-SSR-26": ["Applejack"],
  "3-SSR-27": ["Princess Twilight Sparkle"],
  "3-SSR-28": ["Pinkie Pie"],
  "3-SSR-29": ["Rainbow Dash"],
  "3-SSR-30": ["Rarity"],
  "3-SSR-31": ["Fluttershy"],
  "3-SSR-32": ["Applejack"],
  "3-SSR-33": ["Spike"],
  "3-SSR-34": ["Sweetie Belle"],
  "3-SSR-35": ["Babs Seed"],
  "3-SSR-36": ["Diamond Tiara"],
  "3-SSR-37": ["Silver Spoon"],
  "3-SSR-38": ["Big McIntosh"],
  "3-SSR-39": ["Cheese Sandwich"],
  "3-SSR-40": ["Garble"],
    "3-HR-1": ["Princess Twilight Sparkle"],
  "3-HR-2": ["Pinkie Pie"],
  "3-HR-3": ["Rainbow Dash"],
  "3-HR-4": ["Rarity"],
  "3-HR-5": ["Fluttershy"],
  "3-HR-6": ["Applejack"],
  "3-HR-7": ["Spike"],
  "3-HR-8": ["Muffins"],
  "3-HR-9": ["Applejack, Rarity, RariJack"],
  "3-HR-10": ["Sweetie Belle, Scootaloo"],
  "3-HR-11": ["Applejack, Apple Bloom, Discord"],
  "3-HR-12": ["Gilda, Grandpa Gruff"],
  "3-HR-13": ["Rainbow Dash, Gilda"],
  "3-HR-14": ["Lyra Heartstrings, Sweetie Drops"],
  "3-HR-15": ["Apple Bloom, Scootaloo, Sweetie Belle"],
  "3-HR-16": ["Rainbow Dash, Applejack, AppleDash"],
  "3-HR-17": ["Pinkie Pie, Gummy, Pound Cake"],
  "3-HR-18": ["Princess Twilight Sparkle, Pinkie Pie, TwiPie"],
  "3-HR-19": ["Princess Twilight Sparkle, Spike"],
  "3-HR-20": ["Princess Twilight Sparkle, Fluttershy"],
  "3-HR-21": ["Princess Twilight Sparkle, Pinkie Pie, Applejack, Rarity, Fluttershy, Rainbow Dash, Spike, Discord"],
  "3-HR-22": ["Rarity, Rainbow Dash"],
  "3-HR-23": ["Princess Twilight Sparkle"],
  "3-HR-24": ["Pinkie Pie"],
  "3-HR-25": ["Rainbow Dash"],
  "3-HR-26": ["Rarity"],
  "3-HR-27": ["Fluttershy"],
  "3-HR-28": ["Applejack"],
  "3-HR-29": ["Princess Luna"],
  "3-HR-30": ["Princess Cadance"],
  "3-HR-31": ["Princess Twilight Sparkle"],
  "3-HR-32": ["Pinkie Pie, Gummy"],
  "3-HR-33": ["Rainbow Dash"],
  "3-HR-34": ["Rarity"],
  "3-HR-35": ["Fluttershy, Angel"],
  "3-HR-36": ["Applejack"],
  "3-HR-37": ["Discord"],
  "3-HR-38": ["Starlight Glimmer"],
  "3-HR-39": ["Pinkie Pie, Rarity"],
  "3-HR-40": ["Pinkie Pie"],
  "3-HR-41": ["Spike, Starlight Glimmer"],
  "3-HR-42": ["Princess Twilight Sparkle"],
  "3-HR-43": ["Starlight Glimmer, Trixie"],
  "3-HR-44": ["Princess Twilight Sparkle, Discord"],
  "3-HR-45": ["Applejack, Pinkie Pie, Fluttershy"],
  "3-HR-46": ["Shining Armor, Princess Cadance"],
  "3-HR-47": ["Nurse Redheart, Princess Flurry Heart, Cherry Fizzy"],
  "3-HR-48": ["Apple Bloom, Scootaloo, Sweetie Belle"],
  "3-HR-49": ["Rarity, Sweetie Belle"],
  "3-HR-50": ["Rainbow Dash, Spitfire, Fleetfoot"],
  "3-HR-51": ["Bow Hothoof, Windy Whistles"],
  "3-HR-52": ["Princess Celestia, Princess Luna"],
  "3-HR-53": ["Princess Twilight Sparkle"],
  "3-HR-54": ["Pinkie Pie"],
  "3-HR-55": ["Rainbow Dash"],
  "3-HR-56": ["Rarity"],
  "3-HR-57": ["Fluttershy"],
  "3-HR-58": ["Applejack"],
  "3-HR-59": ["Spike"],
  "3-HR-60": ["Trixie"],
    "3-LSR-1": ["Princess Twilight Sparkle"],
  "3-LSR-2": ["Pinkie Pie"],
  "3-LSR-3": ["Rainbow Dash"],
  "3-LSR-4": ["Rarity"],
  "3-LSR-5": ["Fluttershy"],
  "3-LSR-6": ["Applejack"],
  "3-LSR-7": ["Princess Celestia"],
  "3-LSR-8": ["Princess Luna"],
  "3-LSR-9": ["Starlight Glimmer"],
  "3-LSR-10": ["Trixie"],
  "3-LSR-11": ["Maud Pie"],
  "3-LSR-12": ["Countess Coloratura"],
  "3-LSR-13": ["Zecora"],
  "3-LSR-14": ["Big McIntosh"],
  "3-LSR-15": ["Discord"],
  "3-LSR-16": ["Mistmane"],
  "3-LSR-17": ["Princess Twilight Sparkle"],
  "3-LSR-18": ["Pinkie Pie"],
  "3-LSR-19": ["Rainbow Dash"],
  "3-LSR-20": ["Rarity"],
  "3-LSR-21": ["Fluttershy"],
  "3-LSR-22": ["Applejack"],
  "3-LSR-23": ["Spike"],
  "3-LSR-24": ["Discord"],
  "3-LSR-25": ["Cozy Glow"],
  "3-LSR-26": ["Princess Cadance"],
  "3-LSR-27": ["Flurry Heart"],
  "3-LSR-28": ["Scootaloo"],
  "3-LSR-29": ["Sweetie Belle"],
  "3-LSR-30": ["Apple Bloom"],
  "3-LSR-31": ["Sunset Shimmer"],
  "3-LSR-32": ["King Sombra"],
    "3-UR-1": ["Princess Twilight Sparkle"],
  "3-UR-2": ["Pinkie Pie"],
  "3-UR-3": ["Rainbow Dash"],
  "3-UR-4": ["Rarity"],
  "3-UR-5": ["Fluttershy"],
  "3-UR-6": ["Applejack"],
  "3-UR-7": ["Spike"],
  "3-UR-8": ["Sweetie Belle"],
  "3-UR-9": ["Apple Bloom"],
  "3-UR-10": ["Scootaloo"],
  "3-UR-11": ["Muffins"],
  "3-UR-12": ["Trixie"],
  "3-UR-13": ["Starlight Glimmer"],
  "3-UR-14": ["DJ Pon-3"],
  "3-UR-15": ["Pinkie Pie, Applejack, ApplePie"],
  "3-UR-16": ["Fluttershy, Rarity"],
  "3-UR-17": ["Princess Twilight Sparkle, Rainbow Dash, TwiDash"],
  "3-UR-18": ["Rarity"],
    "3-SGR-1": ["Princess Twilight Sparkle"],
  "3-SGR-2": ["Pinkie Pie"],
  "3-SGR-3": ["Rainbow Dash"],
  "3-SGR-4": ["Rarity"],
  "3-SGR-5": ["Fluttershy"],
  "3-SGR-6": ["Applejack"],
  "3-SGR-7": ["Starlight Glimmer"],
  "3-SGR-8": ["Queen Chrysalis"],
  "3-SGR-9": ["Princess Twilight Sparkle"],
  "3-SGR-10": ["Pinkie Pie"],
  "3-SGR-11": ["Rainbow Dash"],
  "3-SGR-12": ["Rarity"],
  "3-SGR-13": ["Fluttershy"],
  "3-SGR-14": ["Applejack"],
  "3-SGR-15": ["Discord, Princess Celestia, Princess Luna"],
  "3-SGR-16": ["Queen Chrysalis, Cozy Glow, Lord Tirek"],
    "3-ZR-1": ["Princess Twilight Sparkle, Shining Armor"],
  "3-ZR-2": ["Pinkie Pie, Limestone Pie, Marble Pie"],
  "3-ZR-3": ["Rainbow Dash"],
  "3-ZR-4": ["Rarity, Sweetie Belle"],
  "3-ZR-5": ["Fluttershy"],
  "3-ZR-6": ["Applejack, Big McIntosh, Apple Bloom"],
  "3-ZR-7": ["Apple Bloom, Sweetie Belle, Scootaloo, Snips, Snails, Diamond Tiara, Silver Spoon"],
  "3-ZR-8": ["Princess Twilight Sparkle"],
  "3-ZR-9": ["Pinkie Pie"],
  "3-ZR-10": ["Rainbow Dash"],
  "3-ZR-11": ["Rarity"],
  "3-ZR-12": ["Fluttershy"],
  "3-ZR-13": ["Applejack"],
  "3-ZR-14": ["Princess Twilight Sparkle, Pinkie Pie, Applejack, Rarity, Fluttershy, Rainbow Dash"],
    "3-SC-1": ["Princess Twilight Sparkle"],
  "3-SC-2": ["Pinkie Pie"],
  "3-SC-3": ["Rainbow Dash"],
  "3-SC-4": ["Rarity"],
  "3-SC-5": ["Fluttershy"],
  "3-SC-6": ["Applejack"],
  "3-SC-7": ["Fluttershy"],
  "3-SZR-1": ["Princess Twilight Sparkle, Pinkie Pie, Applejack, Rarity, Fluttershy, Rainbow Dash"],
  "3-SZR-2": ["Pinkie Pie, Applejack, Rarity, Fluttershy, Rainbow Dash, Princess Celestia, Princess Luna"],
  "3-SZR-3": ["Princess Twilight Sparkle, Spike"],
};
